### ISSUE TITLE
Static Noise During Certain Cutscenes

### ISSUE THREAD

**Issue by vololo0** [irtimmer/moonlight-embedded#119]
Environment:
Raspberry Pi 2
All Prerequisites installed
OS: Retropie
Game: Mortal Kombat X via Steam.
GFE Version:  2.4.3 (Latest)
Limelight Version: Limelight Embedded 1.2.2 ( with latest libopus.so )
TV and Audio: HDMI -> LG TV ->  Optical out to LG Soundbar
Inputs: Wireless Microsoft mouse keyboard combo + Bluetooth dongle and 2 PS3 controllers.

Issue:
Hi i have an issue with static noises during certain cut scenes of Mortal Kombat X via Steam streamed at 1080p 30fps via HDMI and Static noise through out the game of WatchDogs. It runs as smooth as butter and flawlessly with the exception of the noise issue. 

Tried switching to different resolutions and fps , issue still persist.

**Comment by HazCod** [comment]
Try a different cable, different input on your TV or leaving the optical out unplugged.

**Comment by vololo0** [comment]
HI i have already tried, problem still persist. Thank you for the suggestion. I have also tried a freshly installed Retropie and the problem is still there. I just hear white noise during cut scenes. But when during the actual gameplay the audio is perfect.

**Comment by scoobyd00** [comment]
If its only doing it on a couple of games then it looks like its an issue with GeForce experience.

**Comment by vololo0** [comment]
I tries streaming to my phone and the i had the same issue. @scoobyd00 you are right it the problem with the gfe. Thannk you

**Comment by cgutman** [comment]
Since a few releases ago, GFE stops sending audio packets at all if the program isn't outputting any audio (rather than sending silent samples as they used to). This causes a buffer underrun on the client when the audio stream stops mid-stream. Depending on the client, hardware, OS, etc this can be fine or cause noticeable clicks, pops, etc.

**Comment by vololo0** [comment]
@cgutman hi , Mine is more of a white noise just like this https://www.youtube.com/watch?v=t0I4mTEdAf8. and its not random. Do you know of a fix or workaround for this issue? I have look at many posts and forums but i cant find any problem similiar to mine.

Any my pc specs:

GRAPHICS: GTX 780
CPU : I7 4970k
RAM: 32GB

**Comment by vololo0** [comment]
Found out the issue!! The issue was unique to my setup, i have an apple display with built in speakers and i had many audio devices active. I deactivated the display audio and used NVIDIA High Definition Audio instead to output my pc audio. No more static problem! issue resolved!. Thank you All!!!
