### ISSUE TITLE
GEE 2.4.5 not supported/recognized

### ISSUE THREAD

**Issue by derlala** [irtimmer/moonlight-embedded#124]
hi
on start of limelight.jar it says that gee 2.1.1 is needed - in fact i have 2.4.5.x.

tnx for help 
derlala

**Comment by cgutman** [comment]
On your GeForce machine, open http://127.0.0.1:47989/serverinfo in a browser. Paste the XML on pastebin.com and post a link here.

**Comment by cgutman** [comment]
Nevermind. GFE 2.4.5 is known working with the latest Moonlight clients. Grab an updated jar from here and it should work. https://github.com/irtimmer/moonlight-embedded/releases
