### ISSUE TITLE
Please add VDPAU support

### ISSUE THREAD

**Issue by pomkac** [irtimmer/moonlight-embedded#127]
Hi all! I have Cubietruck, moonlight not working on it. Can you add VDPAU support for SUNXI? 
I'm not a software programmer in C, so it is difficult to add it to moonlight. Please, help. For C developer this is one day. Link for SUNXI-decoder: https://github.com/linux-sunxi/libvdpau-sunxi/blob/master/decoder.c

**Comment by pomkac** [comment]
I wrote the code to support VDPAU. How can I add it to the repository?

**Comment by irtimmer** [comment]
You could fork the repository, commit your changes and fill a pull request. https://help.github.com/articles/fork-a-repo/
Or you could just dump the code somewhere and hope someone else pushes it to the repository.

**Comment by irtimmer** [comment]
I you have troubles committing the code please let me know. I really like to add VDPAU support.

**Comment by pomkac** [comment]
I create commit jn next week. It is necessary to improve the functionality, but I did not have enough time. A lot of work has accumulated. (

**Comment by aPollO2k** [comment]
I'm waiting for this very excited. I own a banana pi and it would be great to run moonlight on it.

**Comment by pomkac** [comment]
http://www.filedropper.com/repo
This is patch to VDPAU support. I'm still going to optimize it, but it is work.

**Comment by irtimmer** [comment]
After making a few changes because the code was based on an older version of Moonlight, I have committed it to the branch [vdpau2](https://github.com/irtimmer/moonlight-embedded/tree/vdpau2).
