### ISSUE TITLE
HTTP request status never checked

### ISSUE THREAD

**Issue by cgutman** [irtimmer/moonlight-embedded#128]
The http_request() function should check the "status_code" and "status_message" attributes before continuing. When an error occurs, GFE returns HTTP 200 with status_code!=200. Failing to check that results in bad behavior like hijacking other streaming sessions (crashing nvstream when input is sent due to the AES key not matching).

**Comment by irtimmer** [comment]
Fixed by 09461caaf91cf7422caa5f700ad469715ff7355e
