### ISSUE TITLE
RaspberryPi OMX Error

### ISSUE THREAD

**Issue by lectrasxt16** [irtimmer/moonlight-embedded#129]
Cloned from Git ( 2.6.15 (tt.mm.jj))
compiled (no error)

Output:
------------------------------
root@raspberrypi:~/moonlight-pi/moonlight-embedded/build# cmake ../
-- The C compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.26.0")
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.0.1e")
-- Found EXPAT: /usr/lib/arm-linux-gnueabihf/libexpat.so (found version "2.1.0")
-- Found ALSA: /usr/lib/arm-linux-gnueabihf/libasound.so (found version "1.0.25")
-- Found Opus: /usr/lib/libopus.so
-- Found Broadcom: /opt/vc/include
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- checking for module 'libevdev'
--   found libevdev, version 1.4.2
-- checking for module 'avahi-client'
--   found avahi-client, version 0.6.31
-- checking for module 'libudev'
--   found libudev, version 175
-- Configuring done
-- Generating done
-- Build files have been written to: /root/moonlight-pi/moonlight-embedded/build
root@raspberrypi:~/moonlight-pi/moonlight-embedded/build# make
Scanning dependencies of target moonlight
[  2%] Building C object CMakeFiles/moonlight.dir/src/mapping.c.o
[  5%] Building C object CMakeFiles/moonlight.dir/src/discover.c.o
[  8%] Building C object CMakeFiles/moonlight.dir/src/xml.c.o
[ 11%] Building C object CMakeFiles/moonlight.dir/src/global.c.o
[ 14%] Building C object CMakeFiles/moonlight.dir/src/input.c.o
[ 17%] Building C object CMakeFiles/moonlight.dir/src/audio.c.o
[ 20%] Building C object CMakeFiles/moonlight.dir/src/connection.c.o
[ 22%] Building C object CMakeFiles/moonlight.dir/src/mkcert.c.o
[ 25%] Building C object CMakeFiles/moonlight.dir/src/http.c.o
[ 28%] Building C object CMakeFiles/moonlight.dir/src/main.c.o
[ 31%] Building C object CMakeFiles/moonlight.dir/src/video.c.o
[ 34%] Building C object CMakeFiles/moonlight.dir/src/client.c.o
[ 37%] Building C object CMakeFiles/moonlight.dir/src/video/fake.c.o
[ 40%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/PlatformSockets.c.o
[ 42%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/Connection.c.o
[ 45%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/ControlStream.c.o
[ 48%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/RtspParser.c.o
[ 51%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/PlatformThreads.c.o
[ 54%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/VideoDepacketizer.c.o
[ 57%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/LinkedBlockingQueue.c.o
[ 60%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/InputStream.c.o
[ 62%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/FakeCallbacks.c.o
[ 65%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/AudioStream.c.o
[ 68%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/SdpGenerator.c.o
[ 71%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/ByteBuffer.c.o
/root/moonlight-pi/moonlight-embedded/third_party/moonlight-common-c/limelight-common/ByteBuffer.c: In function ‘byteSwapInt’:
/root/moonlight-pi/moonlight-embedded/third_party/moonlight-common-c/limelight-common/ByteBuffer.c:24:3: warning: implicit declaration of function ‘htonl’ [-Wimplicit-function-declaration]
/root/moonlight-pi/moonlight-embedded/third_party/moonlight-common-c/limelight-common/ByteBuffer.c: In function ‘byteSwapShort’:
/root/moonlight-pi/moonlight-embedded/third_party/moonlight-common-c/limelight-common/ByteBuffer.c:34:3: warning: implicit declaration of function ‘htons’ [-Wimplicit-function-declaration]
[ 74%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/RtspConnection.c.o
[ 77%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/VideoStream.c.o
[ 80%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/OpenAES/oaes_lib.c.o
[ 82%] Building C object CMakeFiles/moonlight.dir/third_party/moonlight-common-c/limelight-common/OpenAES/oaes_base64.c.o
[ 85%] Building C object CMakeFiles/moonlight.dir/third_party/ilclient/ilclient.c.o
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
[ 88%] Building C object CMakeFiles/moonlight.dir/third_party/ilclient/ilcore.c.o
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
[ 91%] Building C object CMakeFiles/moonlight.dir/third_party/h264bitstream/h264_stream.c.o
[ 94%] Building C object CMakeFiles/moonlight.dir/third_party/h264bitstream/h264_nal.c.o
[ 97%] Building C object CMakeFiles/moonlight.dir/third_party/h264bitstream/h264_sei.c.o
[100%] Building C object CMakeFiles/moonlight.dir/src/video/omx.c.o
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function ‘vcos_timer_delete’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function ‘vcos_timer_reset’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function ‘vcos_timer_cancel’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function ‘vcos_timer_set’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function ‘vcos_timer_create’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function ‘vcos_thread_resume’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function ‘vcos_thread_running’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function ‘vcos_change_preemption’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function ‘vcos_thread_relinquish’ declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function ‘vcos_thread_get_affinity’ declared but never defined [enabled by default]
Linking C executable moonlight
[100%] Built target moonlight
--------------------------------------

When streaming from PC :

Output:
---------------------------------

root@raspberrypi:~/moonlight-pi/moonlight-embedded/build# ./moonlight stream -app "Dirt 3" 192.168.120.160
Initializing platform...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...Can't initialize OMX

----------------------------------------------

**Comment by irtimmer** [comment]
http://rpi.vypni.net/omxcore-failed-to-init-on-raspberry-pi-raspbian/
