### ISSUE TITLE
tarball corrupt?

### ISSUE THREAD

**Issue by darkpavian** [irtimmer/moonlight-embedded#133]
Hi There, 

just downloaded the 

  moonlight-embedded-2.0.tar.xz 

to my raspberry pi 2 running raspbian and tried to uncompress it via

  tar Jxf moonlight-embedded-2.0.tar.xz

but only got

  xz: (stdin): Datei Format nicht erkannt
  tar: Child returned status 1
  tar: Error is not recoverable: exiting now

Is the file corrupt?

**Comment by emeyer1** [comment]
So it isn't compressed in gzip format. The -J parameter is really -xz and the -z is gzip. Try just 

tar -xf moonlight-embedded-2.0.xz
