### ISSUE TITLE
Fake decoder renderer can fill up disk if left running

### ISSUE THREAD

**Issue by mrb113** [irtimmer/moonlight-embedded#148]
If you end up with the fake decoder renderer, it writes the stream to fake.h264 on your disk. This is probably nice for debugging/testing and if there's a way to turn it on in a debug scenario, that'd be sweet.

However, from a user perspective...
Hypothetical steps:
- Build Moonlight Embedded, mess up somehow, no valid decoder renderers 

Expected: 
Error or warning that there are no valid DRs

Actual: 
- Black screen for the stream (confusing, not intuitive where the error is)
- If left unchecked, it could possibly fill up the user's disk (bad, especially if they don't know what the file is)

Not sure how commonly this happens, but it should be a small modification to keep users from hitting this scenario. I"d recommend an error or more advanced logic that allows you to turn it on for testing if you use it, but a warning that requires confirmation from the user before continuing would suffice.

**Comment by irtimmer** [comment]
The fake video output is now only enabled in debug builds (see f99ba40cc92e27dc4cb43921fe4d9bbb02506166)
