### ISSUE TITLE
Compiling on Rpi2 Debian Jessie (OSMC)

### ISSUE THREAD

**Issue by tortilaman** [irtimmer/moonlight-embedded#150]
I'm trying to install moonlight on my Raspberry Pi 2 with OSMC installed, which is based off of Debian Jessie and not Wheezy or Raspbian. As I kind of expected but hoped wouldn't happen, I'm getting some unmet dependencies:

```
The following packages have unmet dependencies:
 moonlight-embedded : Depends: libudev0 (>= 146) but it is not installable
                      Depends: libraspberrypi0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I'm assuming I'll have to compile this, but I'll still run into the problem that the dependencies are unmet with the repositories I have available. Does anybody have experience doing this or can provide assistance?

**Comment by irtimmer** [comment]
For Debian Jessie you need to recompile against libudev1 and somehow install the userland GPU libraries (libraspberrypi0), but I have no idea of where to find them for Debian Jessie

**Comment by tortilaman** [comment]
Thanks for the information. I'll probably just do this in a Debian Wheezy environment then.

**Comment by swetoast** [comment]
http://paste.osmc.io/osikocixix.vbs

came this far before it broke

**Comment by cgutman** [comment]
Looks like you haven't done: git submodule update --init

You might have to rerun cmake after that too.

**Comment by swetoast** [comment]
Yepp worked tnx :D
