### ISSUE TITLE
Raspberry pi 1 1080p 30fps/720p 60fps discarding it's RTP packages

### ISSUE THREAD

**Issue by yakka34** [irtimmer/moonlight-embedded#152]
<h1>Edit: Manually setting the bitrate fixes the problem. The internet usage remains at the same level as before but now packages aren't being dropped.
</h1>
Raspberry pi(turbo overclocked) using wheezy with 4.0 kernel and moonlight repo keeps discarding packages.
I don't remember seeing this happen when I build from sources using debian/raspbian "testing" branch.

pi@raspberrypi ~ $ moonlight stream -1080 -30fps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped middle of a frame
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Waiting for IDR frame
Resync complete
Discarding RTP packet after queue overgrowth
Network dropped middle of a frame
Waiting for IDR frame
Resync complete
Discarding RTP packet after queue overgrowth
Network dropped middle of a frame
Waiting for IDR frame
Resync complete
Discarding RTP packet after queue overgrowth
Network dropped middle of a frame
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Discarding RTP packet queued for too long
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Resync complete
Waiting for IDR frame
Discarding RTP packet after queue overgrowth
Network dropped middle of a frame
Discarding RTP packet after queue overgrowth
Network dropped beginning of a frame
Resync complete
Waiting for IDR frame
Discarding RTP packet queued for too long
Network dropped middle of a frame
Waiting for IDR frame
Resync complete
Loss stats thread terminating #1
Stopping input stream...done
Stopping audio stream...done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Terminating RTSP handshake...done
Cleaning up platform...done
pi@raspberrypi ~ $

**Comment by cgutman** [comment]
These messages indicate that the network is dropping packets. Are you using Ethernet to your computer and Pi?

**Comment by yakka34** [comment]
Yes I'm. on the raspberry end is a cat 6 and on the streaming computer is cat 5 cable. Streaming is limited to cat 5 speed of course but shouldn't 10/100 be more than enough for 1080p 30fps.

**Comment by maverickjesus** [comment]
What bitrate setting did you use?

**Comment by yakka34** [comment]
I would guess that mine was 4250. Basically I tried many settings and 4500 was too high and 3500 too low. Reference steam in-house streaming settings for presets
