### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by arg81** [irtimmer/moonlight-embedded#159]
A very newbie question, I decided to start my project again and give Moonlight a go (was running Limelight).  I notice there are now packages.  I have done as what is documented, but what do I do after? Do I still need to install?  I don't see any folders for Moonlight and if I run the install again I get a "moonlight-embedded is already the newest version"

Any help appreciated.

**Comment by HazCod** [comment]
moonlight is now installed. just run it by typing `moonlight` or whatever.
