### ISSUE TITLE
Ignoring terminal input

### ISSUE THREAD

**Issue by vulcandth** [irtimmer/moonlight-embedded#163]
After exiting moonlight from playing games on my raspberry pi, i'm left with lines upon lines of input left in my shell window filled with characters typed on my keyboard while playing my game. Example (aaaawwwwwwssswwwaaaaawwdddaaaasssss) 

If its possible we should find a way to block input into the background shell.

Let me know if I can explain this any better.

**Comment by Lombra** [comment]
I have this too. What's even worse is that when I navigate some menu (eg Steam) using the keyboard, these keystrokes will be queued up to be executed once Moonlight exits, going through recently entered console commands (up arrow) and executing them!! (enter) That's potentially very harmful.

**Comment by vulcandth** [comment]
Sorry accidentally hit the close button lol.

**Comment by darkpavian** [comment]
yep, that's right. E.g. when using the keyboard to shutdown the stream it is Arrow+up, [Arrow+right, Arrow+right], return, which causes the moonlight command to be executed imidiatly again after shutdown.

**Comment by vulcandth** [comment]
I have a couple idea of how to fix this; When I get home from work i'll fork this repo add my changes, test, and suggest a merge.

**Comment by vulcandth** [comment]
#166

**Comment by irtimmer** [comment]
Should now be solved by #167
