### ISSUE TITLE
Four controllers - Keyboard always takes input slot

### ISSUE THREAD

**Issue by adzlc** [irtimmer/moonlight-embedded#170]
Hi all,

Not sure if I am the only one with this issue; I have 4 Xbox controllers hooked via a Raspberry pi to /dev/input/js0-3 (I've written udev rules so they are always these 4) and for other emulators this works fine but not for moonlight. My problem is the last player is ALWAYS the keyboard; 1-3 players will be a controller (regardless of how many controllers I connect). I have found this to be the case for every game, including games I know I can play with 4 controllers locally.

I have tried using -input but it appears that requires /dev/input/event which I believe can be random.

Has anyone come up with a solution?

Is it possible for the -input code to be altered (or a new argument added) to accept JS inputs?

I don't think my fundamental controller set up is a problem; I can play 4 players with this on mame and N64.

EDIT:
So I learnt enough C to be able to generally read the code and I recompiled it with some printf's so I could see what is happening. If I specify the map/inputs only those get loaded according to some prints I put into the [input.c changing l187](https://github.com/irtimmer/moonlight-embedded/blob/master/src/input.c#L187); without the input args I get 6 events registered (4 controllers + a keyboard attached, no clue what the 6th was).

It appears that it is random which controller will not work. It is not usable in the Steam interface so I am guessing its at that point of entry something is wrong. I have two wired and two wireless controllers and I did think it may be a problem with two wireless but I have had two wireless/one wired working so I have ruled that out.

I don't know where in the code the inputs get passed to the Steam app. I will have to check.

**Comment by adzlc** [comment]
I've tried creating a udev rule for the events as well; it would seem that the first device is always failing when there are four. I am running (without carriage returns):

```
moonlight stream -mapping xbox.map -input /dev/input/event4 -mapping xbox.map -input 
/dev/input/event5 -mapping xbox.map -input /dev/input/event6 -mapping xbox.map -input 
/dev/input/event7 -app Steam <IP-HERE>
```
This produces an error 'failed to open device: /dev/input/event4' . I can run evtest on all of these event4-7 though suggesting my udev rule is generally working (although I think I have broken the keyboard heh).

Before attempting to set the inputs I was just running:

```
moonlight stream -mapping xbox.map  -app Steam <IP-HERE>
```

**Comment by adzlc** [comment]
I've tested all of the games locally vs streamed and all appear to support 4 controllers over a keyboard which suggests to me the keyboard is perhaps overriding one of the inputs even if you specify 4. I don't particularly know C so am not 100% sure if this is true so its just a hunch.

**Comment by Spirit3s** [comment]
Same problem

**Comment by cgutman** [comment]
This is fixed in common-c by https://github.com/moonlight-stream/moonlight-common-c/commit/40478fc19b9e5e5f6e7e153f97cdb0d21b53573e
