### ISSUE TITLE
OSMC support in .deb package

### ISSUE THREAD

**Issue by dodslaser** [irtimmer/moonlight-embedded#172]
Support for OSMC isn't provided by the .deb on your repo. This can easily be fixed by adding ```rbp-userland-osmc``` as an alternative for ```libraspberrypi0``` in the dependencies. I've tested this myself, and it doesn't seem to give any problems so far.

**Comment by irtimmer** [comment]
Patches are merged. So next release will also work on OSMC

**Comment by daniele-athome** [comment]
Using `distro=raspbian codename=bullseye` for the install script and I still have a hard dependency on `libraspberrypi0`. What am I doing wrong?
