### ISSUE TITLE
Beaglebone Black support?

### ISSUE THREAD

**Issue by jevogel** [irtimmer/moonlight-embedded#174]
I figured moonlight-embedded might work for Beaglebone Black (running Debian Stretch and lxde), but I have run into some problems. At one point I was able to build moonlight-embedded and run it, but video was not functional (audio and controls did work though). I decided to do a clean clone of the repo and do a rebuild, but doing that I ran into the missing BROADCOM/FREESCALE issue. Looking at some of the issues on here, it seems that this issue is generally fixed by installing the Raspberry Pi userland libraries. Is there an equivalent way to solve this issue for the Beaglebone Black?

**Comment by irtimmer** [comment]
Currently video output is only supported on Raspberry Pi (Broadcom libraries) and i.MX6 devices (Freescale). Even with those libraries you wouldn't magically get Beaglebone support. Someone first need to code the support for the VPU (Hardware Video Decoder) of the Beaglebone.
