### ISSUE TITLE
error while loading shared libraries: livcpu.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dlrdlrdlr** [irtimmer/moonlight-embedded#178]
This is on a raspberry pi 2 arch linux. 

opus, expat, openssl, alsa-lib, avahi and libevdev are installed and up to date. 
Installed from the moonlight repo version 2.0.2-1

**Comment by irtimmer** [comment]
Version 2.1 and higher should no longer complain about missing Freescale libraries on the Raspberry Pi
