### ISSUE TITLE
vmcam source code

### ISSUE THREAD

**Issue by BenjaminFaal** [irtimmer/moonlight-embedded#183]
Dag Irtimmer,

Ik heb de source code van vmcam nodig.

Met vriendelijke groet,

Benjamin

**Comment by BenjaminFaal** [comment]
Laat de source maar zitten, ik heb hem inmiddels maar ik heb nu een fout dat ie vastloopt bij ssl-client error -1 enig idee?

**Comment by irtimmer** [comment]
THIS ISN'T VMCAM!!!
