### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by demonLaMagra** [irtimmer/moonlight-embedded#185]
command moonlight pair host not working. 

I installed moonlight using the apt-get command and adding the repository to my sources and all went well but now it will not connect to my PC. I have all the correct set up but thinking I may be missing something (perhaps overlooked?)

Any help, greatly appreciated.

**Comment by ilovemetrics** [comment]
I used this same install method and am having this issue as well.

**Comment by Chrisko34** [comment]
Me too.

**Comment by Chrisko34** [comment]
anyone who has a solution for this problem?

**Comment by irtimmer** [comment]
Without providing any more information than "it doesn't work" there's no way someone is able to help you.
