### ISSUE TITLE
v2.1 breaks streaming on Pi (Raspbian)

### ISSUE THREAD

**Issue by cgutman** [irtimmer/moonlight-embedded#188]
I'm running a fully updated Rasbian wheezy on my Pi 2. I installed Moonlight via the Rasbian package repo. After installing, I get the error "Platform 'default' not found" when trying "moonlight pair 192.168.1.2" and "moonlight stream 192.168.1.2". This bug alone prevents streaming from working at all.

My fixes are in #187

**Comment by irtimmer** [comment]
Fixes are merged and new version has been released.
