### ISSUE TITLE
Bad version in Packages.gz

### ISSUE THREAD

**Issue by dodslaser** [irtimmer/moonlight-embedded#189]
The version number for moonlight-embedded in Packages.gz on the debian repo is 2.1.**0**-1 rather than 2.1.**1**-1. This causes apt-get to return a 404.

```shell
E: Failed to fetch http://archive.itimmer.nl/raspbian/moonlight/pool/main/m/moonlight-embedded/moonlight-embedded_2.1.0-1_armhf.deb  404  Not Found
```

**Comment by scoobyd00** [comment]
Getting the same error here

**Comment by irtimmer** [comment]
Try by rerun 'apt-get update' as there's nothing wrong with packages.gz. Propably this is just a cache issue.

**Comment by scoobyd00** [comment]
Ive dont multiple re runs of apt-get update but still get the same error as dodslaser.
Dont know if it takes time to sort the cache out but ive rebooted and re run apt-get update and still the same

**Comment by scoobyd00** [comment]
Fixed now .. Took a while to re cache
