### ISSUE TITLE
RTSP DESCRIBE request failed:500 

### ISSUE THREAD

**Issue by scoobyd00** [irtimmer/moonlight-embedded#191]
Ok, ive gone for a new Windows 10 install .

Ive succesfully paired moonlight but when i come to run the stream i get the following error message.

Starting RTSP handshake...RTSP DESCRIBE request failed:500 
failed: -1

Ive disabled windows firewall, got static ip addresses for both my raspberry pi and pc but i still cant get the stream to work.

It worked fine in windows 8.1

Any ideas its driving me crazy.

**Comment by Ilos** [comment]
try to reinstall your drivers and Geforce Experience.

**Comment by irtimmer** [comment]
Duplicate of #180

**Comment by scoobyd00** [comment]
Still getting the Starting RTSP handshake...RTSP DESCRIBE request failed:500 
failed: -1 error
Tried re installing drivers and experience but the stream wont start. Pairing is fine.

Anyone know what the error 500 means?.
