### ISSUE TITLE
Audio output

### ISSUE THREAD

**Issue by Zega** [irtimmer/moonlight-embedded#199]
Hello again,

I am sorry, but I can't find the information on the net, is moonlight-embedded able to get audio passthroug from the hdmi?

If not, is it possible and how to get 5.1 DTS or dolby audio output?

Thank you!

**Comment by cgutman** [comment]
At the moment, GameStream only supports 2 channel audio.

**Comment by Zega** [comment]
@cgutman Thank you for your answer, I didn't know that, it is really a pain in the a@#!!

Do you know if something is planned by nvidia to support 5.1? I don't really know why technically speaking it can't support 5.1.
