### ISSUE TITLE
Can't compile OSMC Raspberry PI

### ISSUE THREAD

**Issue by ro8in** [irtimmer/moonlight-embedded#200]
When I do cmake ../

I get the following error

You have called ADD_LIBRARY for library moonlight-common without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
CMake Error: CMake can not determine linker language for target: moonlight-common
CMake Error: Cannot determine link language for target "moonlight-common".

I don't know how to fix this?

**Comment by darkpavian** [comment]
Did you init/update the submodules?
You have to call "git submodules init" and then "git submodules update" inside the moonlight-embedded directory to initialize the moonlight-common submodule.

**Comment by lhotamir** [comment]
I am experiencing the same problem. When I call:

    git submodule update

I get following error:

    fatal: reference is not a tree: 2d35d7262ffe79925114d4b5e331e52c6a436d9f
    Unable to checkout '2d35d7262ffe79925114d4b5e331e52c6a436d9f' in submodule path 'third_party/moonlight-common-c'

**Comment by Ilos** [comment]
Try out: "Git reset --hard"
Then "Git submodule update --init"

**Comment by rhaleblian** [comment]
Thanks @darkpavian that worked for me. The update command appears to instead be
    git submodule update
