### ISSUE TITLE
Loss Stats: Transaction failed: 104 after Input Stream... Done.

### ISSUE THREAD

**Issue by Pilotzi** [irtimmer/moonlight-embedded#201]
Hi there,

i installed moonlight-embedded on my pi b rev 2 from the repo via apt-get. When i'm starting moonlight after pairing it with my windows 7 ultimate pc, with "moonlight stream" it shows the bootup of steam and after about one second the stream stops and it shows the message "Loss Stats: Transaction failed: 104" right after "Input stream...done" in the console. 

I forwarded all for nvidia gamestreaming neccessary ports in my Fritz!Box 7360 Router and also opened them in my windows firewall.I even disabled the windows firewall but nothing helped.

Thanks for your help.

**Comment by hersftw** [comment]
Any news on this? I'm having the same issue.
