### ISSUE TITLE
Can't Map Wireless Xbox 360 Controller

### ISSUE THREAD

**Issue by amirgreen** [irtimmer/moonlight-embedded#214]
Hello,
I encountered  a problem in Moonlight.
I can't map my xbox 360 controller. I downloaded the xboxdrv and I can get the input from there.
But, when I'm trying to map the controller in Moonlight, I cant get input at all.
Also if I'm trying to stream with a downloaded mapping file and choose the controller input, it doesn't work.

**Comment by polzy** [comment]
Create xbox.map and paste this : 

abs_x = 0
abs_y = 1
abs_z = -1
reverse_x = false
reverse_y = true
abs_rx = 3
abs_ry = 4
abs_rz = -1
reverse_rx = false
reverse_ry = true
abs_deadzone = 0
abs_dpad_x = 17
abs_dpad_y = 16
reverse_dpad_x = false
reverse_dpad_y = false
btn_north = 308
btn_east = 305
btn_south = 304
btn_west = 307
btn_select = 314
btn_start = 315
btn_mode = 316
btn_thumbl = 317
btn_thumbr = 318
btn_tl = 310
btn_tr = 311
btn_tl2 = 312
btn_tr2 = 313
btn_dpad_up = -1
btn_dpad_down = -1
btn_dpad_left = -1
btn_dpad_right = -1

launch  moonlight with  :  sudo moonlight stream -1080 -60fps XXX.XXX.XXX.XXX -app Steam -mapping xbox.map
