### ISSUE TITLE
Windows 10 pairing not occuring

### ISSUE THREAD

**Issue by theharleyquin** [irtimmer/moonlight-embedded#221]
Are there any tweaks/changes needed to the Windows firewall to allow pairing? I tried to pair with my PC and I get the ping from the moonlight output, but don't get a prompt on the Windows PC.

**Comment by scoobyd00** [comment]
There shouldnt be any other changes you need to make. Windows 10 is still in its early stages and ive had all sorts of issues trying to run moonlight on it.
Some people are running it fine but i think its all down to your hardware/setup.
I was able to pair with my PC succesfully but when i come to run the stream i get rtsp errors.

Dont have any issues with windows 8.1
