### ISSUE TITLE
RTSP Describe Request failed:500

### ISSUE THREAD

**Issue by pdawg17** [irtimmer/moonlight-embedded#223]
I hadn't used this for awhile but when I went to use it today I got this error (had it working perfectly before). Can anyone confirm 2.1.1 is still working with up-to-date Nvidia drivers and Experience?

**Comment by scoobyd00** [comment]
I've had this same problem on my windows 10 system.. 
Never got to find out wrist the error meant or how to solve it.
Did a fresh install of windows 10 and it started working again.. Hopefully it will stay like this

**Comment by scoobyd00** [comment]
Did you fix the issue?

**Comment by SunNoise** [comment]
I'm getting the same issue in win 8.1 with the driver 358.50 (GTX 960)
I have moonlight 2.1.1-1 i believe. I got it from the repository:
deb http://archive.itimmer.nl/raspbian/moonlight wheezy main

**Comment by pdawg17** [comment]
I'm on wired so that's not the problem for me...

**Comment by irtimmer** [comment]
RTSP Describe Request failed: 500 often requires a reinstall of the Geforce driver and Geforce Experience software and otherwise please provide a Wireshark dump
