### ISSUE TITLE
5.1 audio and 4k in new geforce beta driver.

### ISSUE THREAD

**Issue by likelyeatenbyagrue** [irtimmer/moonlight-embedded#225]
Nvidia beta driver now supports 4k/5.1 audio. Would love 5.1 on my pi 2. 

http://www.geforce.com/geforce-experience/gfe-beta

Edit: It was added to moonlight common: 

https://github.com/moonlight-stream/moonlight-common/commit/0ced1493cdf3cdfb08c8419f1fcefc0c067fb145

**Comment by cgutman** [comment]
I've added support for 5.1 surround sound into common-c here: https://github.com/moonlight-stream/moonlight-common-c/commit/a13e68b0421814cb9acf93d4d4466e14700e4e39

It needs a small amount of work and testing to confirm that the channels are in the right order. Does anyone have a 5.1 config connected to their Pi?

**Comment by likelyeatenbyagrue** [comment]
yes. so if i apt-get update i should be set?

**Comment by cgutman** [comment]
You'll have to build from source. I've made the required changes in my experimental_surround branch.

Clone https://github.com/cgutman/moonlight-embedded.git then checkout experimental_surround.

You'll need to be on the latest GFE beta update. Pass the -surround option to Moonlight to have it stream 5.1 surround. I don't have a 5.1 system to test on. Anyone who can build and test, please report results.

**Comment by likelyeatenbyagrue** [comment]
When running:
git submodule update --init

I get:
fatal: reference is not a tree: 81ecd32e833035d89538a5a5c78b4ad61ecdceb5
Unable to checkout '81ecd32e833035d89538a5a5c78b4ad61ecdceb5' in submodule path 'third_party/moonlight-common-c'

FYI: I bought a nvidia shield last week and am running on beta channel. So my pc is set to stream 5.1 with supported games (i have it fully working). In other words once i get this built I will be able to tell you with 100% certainty whether the pi is outputting sound like an official nvidia device. (for anyone wanting to stream 5.1, you don't need beta graphics card drivers, only beta geforce experience. Furthermore, nvidia's list of supported 5.1 games is rather limited at the moment so don't expect every game to work out of the box. List of games is here: https://forums.geforce.com/default/topic/885630/gamestream/supported-gamestream-games-for-4k-and-5-1-/ ).

**Comment by cgutman** [comment]
Go to the third_party/moonlight-common-c directory and run: git remote set-url origin https://github.com/moonlight-stream/moonlight-common-c.git

**Comment by likelyeatenbyagrue** [comment]
Ok got it compiled and running. Some interesting observations:

When running my shield and gamestreaming I get PCM audio no matter what. So the shield does the decoding and if the game supports surround i get it. 

With the pi I am getting pro logic (not PCM) no matter what...however when running -surround, all games go through all speakers. Even unsupported games. I am guessing this is no different than doing speaker fill on my receiver?

**Comment by cgutman** [comment]
I suspected that we might have issues with PCM surround on the Pi. Others have had issues too. Pro Logic looks like stereo to 5.1 upmixing (which is what you heard).

Can you give details on how exactly your Pi is set up? Kernel version, distro, any audio tweaks you've done?

Can you paste the output of this command: tvservice -a

**Comment by likelyeatenbyagrue** [comment]
Done absolutely no audio tweaks on the pi. It is hdmi out to my yamaha rx-v463 hdmi in. Then back out to my tv. 

uname -a:
Linux shellbeach 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

lsb_release -a:
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

tvservice -a: 

     PCM supported: Max channels: 8, Max samplerate: 192kHz, Max samplesize 24 bits.
     AC3 supported: Max channels: 6, Max samplerate:  48kHz, Max rate  640 kb/s.
     DTS supported: Max channels: 7, Max samplerate:  96kHz, Max rate 1536 kb/s.

**Comment by cgutman** [comment]
Ok, you're pretty much set up the same way I am. The PCM max channels value seems like we should be in good shape. Mine is 2, presumably because I'm not hooked up to a surround system.

You probably didn't see my last edit in time. I put it below:

Can you also see whether either of these 2 commands play audio on all speakers:
speaker-test -Dplug:surround51 -c6 -twav
speaker-test -Dplug:sysdefault -c6 -twav

**Comment by likelyeatenbyagrue** [comment]
First command : unknown PCM cards.pcm.surround51

Second command
Only hear front right and left.

**Comment by cgutman** [comment]
Ok, so we're missing something here with ALSA it seems. You said you've got a Shield setup that works. Can you try Moonlight Android to confirm the surround logic is correct? Instructions here: http://forum.xda-developers.com/showpost.php?p=63454765&postcount=2906 (check the surround checkbox in settings)

I'll continue looking at the ALSA stuff.

**Comment by likelyeatenbyagrue** [comment]
Installed beta moonlight on shield. Works perfect. 5.1 in supported games. 2.1 in non supported.

**Comment by bdunks22** [comment]
I also tried to install and see if I could get it working on my 5.1 system but all I got was regular stereo. I'm not sure if I passed the -surround option to moonlight properly though.

**Comment by cgutman** [comment]
I think the Pi may need a kernel patch to support 5.1 PCM output via ALSA.

**Comment by bdunks22** [comment]
How do I pass the surround option to moonlight?

**Comment by irtimmer** [comment]
Support for 5.1 is in master. Correct working depends on correct configuration of the connected surround set.
