### ISSUE TITLE
Input: send() failed.  Alsa error in writei: -11

### ISSUE THREAD

**Issue by crafty615** [irtimmer/moonlight-embedded#226]
My raspberry pi was working and streaming steam perfect less than a week ago. I took it to a friend's apartment and it stilled worked as we used it to play my steam games. I finally got around to plugging it all back in at my apartment.  
When i start the stream I gain control of my main pc with my pi keyboard, but the stream does not show up on the pi, it just stays on the desktop as if nothing happened.  After a few seconds I get those errors then the stream says it is stopped.
I do not know what could have changed to make this happen.

**Comment by irtimmer** [comment]
Try a newer version of Moonlight Embedded or provide some more information so the bug can actually be debugged.
