### ISSUE TITLE
moonlight as input ( disable video and audio stream) 

### ISSUE THREAD

**Issue by snakecc** [irtimmer/moonlight-embedded#230]
I want to modify code to disable streaming video and audio and allow only input. 
where do I start, how to do that.

**Comment by irtimmer** [comment]
Since commit 3461d1711971e83136d2b3e5cc9e537589ec6e63 you can use `--platform fake` to disable audio and video. But notice a video and audio stream will still be requested and take some bandwidth of your connection.
