### ISSUE TITLE
Platform 'default' not found

### ISSUE THREAD

**Issue by grm** [irtimmer/moonlight-embedded#232]
i own a rpi2 on which i installed OSMC, and i wanted to make it work with moonlight-embedded.

But it seems that moonlight embedded package only work with wheezy and not jessie releases.

I managed to compile everything by upgrading the pi to the stretch version of debian, but now, when I try to launch moonlight i have this strange issue, and even in tickets #190 #192 and #193 does not have the answer (they are only talking about a packaging issue) : Platform 'default' not found

So, I have wo questions 
- how this issue has been resolved in packaging ? (ticket #192)
- Is there a way to install moonlight-embedded in the latest version of osmc ?

Thanks in adavance for your answer

**Comment by Makkaan** [comment]
I have this problem too and i have been trying to reinstall the complete system twice..
