### ISSUE TITLE
Compilation errors??

### ISSUE THREAD

**Issue by Haris1977** [irtimmer/moonlight-embedded#234]
I am trying to compile the latest developer beta version instead of the latest release version (as i want the input controller fix). First i downloaded and installed cmake/make commands with:

sudo apt-get install build-essential
wget http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz
tar xzf cmake-3.2.3.tar.gz
cd cmake-3.2.3
./configure
sudo make install  (the last 2 commands took a really long time!!!!)

Then i used: 

sudo apt-get install git

git clone https://github.com/irtimmer/moonlight-embedded.git

cd moonlight-embedded

sudo apt-get install libopus0 libexpat1 libasound2 libudev0 libavahi-client3 libcurl3 libevdev2 libraspberrypi0 libssl-dev libopus-dev libasound2-dev 

libudev-dev libavahi-client-dev libcurl4-openssl-dev libevdev-dev cmake ibraspberrypi-dev build-essential

mkdir build

cd build/

cmake ../ 

make

make install

cd ~

But when running the cmake ../ i got these errors:

~/moonlight-embedded/build $ cmake ../
CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineSystem.cmake:175                                                                                                              (file):
  file failed to open for writing (Permission denied):

    /home/pi/moonlight-embedded/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

CMake Error: Could not open file for write in copy operation /home/pi/moonlight-                                                                                                             embedded/build/CMakeFiles/3.2.3/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineSystem.cmake:187                                                                                                              (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake                                                                                                             :125 (file):
  file problem creating directory:
  /home/pi/moonlight-embedded/build/CMakeFiles/3.2.3/CompilerIdC
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID_BUILD)
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:108 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake                                                                                                             :125 (file):
  file problem creating directory:
  /home/pi/moonlight-embedded/build/CMakeFiles/3.2.3/CompilerIdC
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID_BUILD)
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:108 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake                                                                                                             :125 (file):
  file problem creating directory:
  /home/pi/moonlight-embedded/build/CMakeFiles/3.2.3/CompilerIdC
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake:39 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID_BUILD)
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:108 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake                                                                                                             :585 (file):
  file failed to open for writing (Permission denied):

    /home/pi/moonlight-embedded/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCompilerId.cmake:48 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID_VENDOR)
  /usr/local/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:108 (CMAKE_DE                                                                                                             TERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)

-- The C compiler identification is unknown
CMake Error: Could not open file for write in copy operation /home/pi/moonlight-                                                                                                             embedded/build/CMakeFiles/3.2.3/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeDetermineCCompiler.cmake:                                                                                                             172 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

CMake Error: Could not find cmake module file: /home/pi/moonlight-embedded/build                                                                                                             /CMakeFiles/3.2.3/CMakeCCompiler.cmake
-- Check for working C compiler: /usr/bin/gcc
CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:35 (f                                                                                                             ile):
  file failed to open for writing (Permission denied):

    /home/pi/moonlight-embedded/build/CMakeFiles/CMakeTmp/testCCompiler.c
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:47 (t                                                                                                             ry_compile):
  Unknown extension ".c" for file

    /home/pi/moonlight-embedded/build/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

-- Check for working C compiler: /usr/bin/gcc -- broken
CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:58 (f                                                                                                             ile):
  file failed to open for writing (Permission denied):

    /home/pi/moonlight-embedded/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

CMake Error at /usr/local/share/cmake-3.2/Modules/CMakeTestCCompiler.cmake:61 (m                                                                                                             essage):
  The C compiler "/usr/bin/gcc" is not able to compile a simple test program.

  It fails with the following output:

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)

-- Configuring incomplete, errors occurred!
See also "/home/pi/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".
CMake Error: Unable to open check cache file for write. /home/pi/moonlight-embed                                                                                                             ded/build/CMakeFiles/cmake.check_cache

Any thoughts???

**Comment by RockyGateway** [comment]
I have a few things you can try:

After you cd moonlight-embedded, use this:

git submodule update --init

then run the rest.

If that doesn't work, use sudo with cmake ../, make, and make install after mkdir build.

I made a script that I use when I want to install Moonlight-Embedded if you want it, I've only tried it out on Jessie, though

**Comment by Haris1977** [comment]
I used git submodule option. Then i tried to install dependancies and i get errors:

sudo apt-get install libopus0 libexpat1 libasound2 libudev0 libavahi-client3 libcurl3 libevdev2 libraspberrypi0 libssl-dev libopus-dev libasound2-dev libudev-dev libavahi-client-dev libcurl4-openssl-dev libevdev-dev cmake ibraspberrypi-dev build-essential
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libevdev-dev
E: Unable to locate package ibraspberrypi-dev

And in sudo cmake ../ i got this:

 sudo cmake ../
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find CEC (missing:  CEC_INCLUDE_DIRS CEC_LIBRARIES) (Required is at least version "3.0")
-- checking for module 'libevdev'
--   package 'libevdev' not found
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:23 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/pi/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".

**Comment by RockyGateway** [comment]
According to the Wiki you're suppose to use "git submodule update --init" after installing dependencies. I remember actually having issues getting that to work if I didn't install the dependencies first. Also you could try installing the latest cmake instead of using that older version:

https://cmake.org/files/v3.4/cmake-3.4.0-rc2.tar.gz

**Comment by Haris1977** [comment]
Thanks i will try it when i get the time:)

But what about missing dependancies isuue?

I got 

E: Unable to locate package libevdev-dev
E: Unable to locate package ibraspberrypi-dev

when installing them

**Comment by Haris1977** [comment]
Well. For my missing packages. I did had misspelled libraspberrypi-dev:( 

But i continue to have error when trying to download "libevdev-dev" as a standalone package. I get:

sudo apt-get install libevdev-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libevdev-dev

So any other way to install it?
