### ISSUE TITLE
No audio RPI2

### ISSUE THREAD

**Issue by dieterhatnkleinen** [irtimmer/moonlight-embedded#239]
Latest Moonlight compiled from source, GFFE 2.7 Beta, Raspi 2 OSMC
I wanted to try the 5.1 surround option.
Now I don't have audio on my RPI 2 at all, not even if I remove the -surround option.

**Comment by egast** [comment]
I have exactly the same problem. When I start the streaming with the surround flag I don't have any audio on my RPI and PC. In fact, audio on my PC is completely gone. I have to restart my pc to get  audio working again.

**Comment by irtimmer** [comment]
Reinstall GFE (and the audio drivers) as sometimes bacause of the audio driver of NVidia isn't working correctly their is no sound send to Moonlight Embedded.
