### ISSUE TITLE
Unable to locate package libevdev-dev (raspbian wheezy)

### ISSUE THREAD

**Issue by Haris1977** [irtimmer/moonlight-embedded#240]
I continue having errors when trying to download "libevdev-dev" as a standalone package. I get:

sudo apt-get install libevdev-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libevdev-dev

So any other way to install it?

Rasp1, model b, 512 mb ram, latest raspbian image

**Comment by burgler00** [comment]
Go to the last post in issue [#135](https://github.com/irtimmer/moonlight-embedded/issues/135) .  I just used those directions on a pi 2 and it worked without having to go through the install instructions in the wiki.

**Comment by Haris1977** [comment]
So there is no need in installing dependencies or cmake? Only following this?

"Add this line to your /etc/apt/sources.list

deb http://archive.itimmer.nl/raspbian/moonlight wheezy main

Install the package using

apt-get update
apt-get install moonlight-embedded"

**Comment by georgcmef** [comment]
Where can i get the libevdev-dev? Every link i see for the link is broken.

**Comment by Haris1977** [comment]
Try:

wget http://archive.raspbian.org/raspbian/pool/main/libe/libevdev/libevdev-dev_1.4.5%2bdfsg-1_armhf.deb
wget http://archive.raspbian.org/raspbian/pool/main/libe/libevdev/libevdev-tools_1.4.5%2bdfsg-1_armhf.deb
wget http://archive.raspbian.org/raspbian/pool/main/libe/libevdev/libevdev2_1.4.5%2bdfsg-1_armhf.deb
sudo dpkg -i libevdev*

If anyone knows the full ssh commands (from scratch till end) to compile and install the up to date latest beta moonlight-embedded (cmake, dependancies, git clone etc), please share with us

Thanks

**Comment by georgcmef** [comment]
ok awesome thanks. dit compiles with no errors but i get this error when i try to run moonlight

moonlight: symbol lookup error: moonlight: undefined symbol: LiInitializeStreamConfiguration

**Comment by irtimmer** [comment]
Compile instructions are available on the wiki https://github.com/irtimmer/moonlight-embedded/wiki/Compilation
