### ISSUE TITLE
arch linux + Orange pi -  Platform 'default' not found

### ISSUE THREAD

**Issue by k-zy** [irtimmer/moonlight-embedded#243]
hello,

I'm trying to use moonlight-embedded on arch linux 
"Linux OrangePi 3.4.39 #1 SMP PREEMPT Mon Oct 12 12:02:29 CEST 2015 armv7l GNU/Linux"

I have follow this : https://github.com/irtimmer/moonlight-embedded/wiki/Packages

When i want to pair my computer, i have this error : 
[root@OrangePi ~]# moonlight pair 192.168.1.123
Platform 'default' not found

**Comment by k-zy** [comment]
My bad, this is not a raspberry Pi platform.
Maybe there is a way to port moolight-embedded on Orange Pi (or Banana pi) ?
I'm using Loboris's  linux distribution form :
 http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=342&extra=page%3D1

**Comment by k-zy** [comment]
I can't succeed to compile moonlight embedded for my platform.
Does the linux Arch ARM package is design only for Rpi and I.mX device ?

**Comment by irtimmer** [comment]
Duplicate of #232

**Comment by phyrexia** [comment]
OrangePi is different than Raspberry , i think you could add support for this boards.
