### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by sirus887** [irtimmer/moonlight-embedded#251]
Hi, 
I am attempting streaming over a LAN via Powerline adapters. Im paired up successfully, however when trying to run steam I get an error RTSP DESCRIBE request failed: -1﻿.

Uninstalled all NVIDIA software in safe mode and reinstalled it again but to no joy.

Any idea why I am failing here?

System has Msi 970, 4790k and 8gb.

Note it worked as limelight but now that not working most likely due to geforce experience

**Comment by Haris1977** [comment]
Did you use gfe 2.4.5.57 or the latest? If not, please use the 2.4.5.57 version

**Comment by cgutman** [comment]
Duplicate of #245

**Comment by sirus887** [comment]
Thanks that seems to work. Now just got to take care of the sound and control mapping. Thanks.
