### ISSUE TITLE
OSMC stopped working

### ISSUE THREAD

**Issue by kaasszje** [irtimmer/moonlight-embedded#253]
all of the sudden the stream won't show at my raspberry pi anymore.
I'm using osmc.
And doing what I've always done:
sudo systemctl stop mediacenter
sudo modprobe snd_bcm2835
moonlight stream -720 -60fps -mapping xbox.map -app Steam
(with or without ip)

The stream starts on my pc. however it does not show at my raspberry.

**Comment by irtimmer** [comment]
Try a newer release or provide some more debug information.
