### ISSUE TITLE
No way to set 30fps through config file

### ISSUE THREAD

**Issue by josephcricket** [irtimmer/moonlight-embedded#257]
I've seen that there's probably a bug on the config file loading system that forbids the program from reading the FPS and always defaults to 60fps  when using config file (not set by argument).

Looks like there's no loading of the key "fps" from the config file anywhere in the config code, and so it uses the default value of 60 fps unless you also pass the argument -30fps.

**Comment by irtimmer** [comment]
Fixed by commit @dba74524c7f070d6c66b0901f744ac17891df417
