### ISSUE TITLE
xbox360.conf mappings dont work

### ISSUE THREAD

**Issue by SJBooth** [irtimmer/moonlight-embedded#258]
How do I edit these in ssh. It seems as if buttons X and Y are mixed up

**Comment by 7hunderbug** [comment]
Have you read the documentation? : https://github.com/irtimmer/moonlight-embedded/wiki/Usage
You can create your own mapping file for your controller.

**Comment by irtimmer** [comment]
Fixed with 41c58974d732720a303f97c0867ea26aa4b2567d
