### ISSUE TITLE
wired xbox360 controller acts wrong

### ISSUE THREAD

**Issue by thtl1999** [irtimmer/moonlight-embedded#259]
with my android phone, my wired MS xbox360 controller acts strange.
it repeat signal. i just pressed 'A' then it repeat 'A' like turbo mode.
it seems the repeating issue is only for righted buttons.
the 'L' button works well and also stick. but the 'R' and ABXY doesn't
i tried my other controllers and they work very well.
i can stop repeating by plug out my OTG and plug in again.
however i can not press single 'A' so i never play with my xbox controller.
i don't know what is wrong.

**Comment by 7hunderbug** [comment]
You've logged your issue against the wrong Github project. Moonlight-embedded is for the Raspberry Pi, CuBox-i and Hummingboard, not Android.

You should log your issue against the Android version: https://github.com/moonlight-stream/moonlight-android
