### ISSUE TITLE
Run individual game (not Steam app)

### ISSUE THREAD

**Issue by Haris1977** [irtimmer/moonlight-embedded#265]
I have added dirt3.exe in my GeForce Experience ==> preferences ==> shield tab (or should i add it on Games tab?).

But what is the exact command to run it?

**Comment by substring** [comment]
did you try a moonlight list command ?

**Comment by Haris1977** [comment]
Yes i did. I get a 1. DSS Launcher and 2. Steam

But how do i run number 1?

**Comment by substring** [comment]
like that :
moonlight stream -app "DSS Launcher" IP

**Comment by Haris1977** [comment]
Thanks will try it asap. I have problem inserting the " symbol,but i think this has to do with keyboard layout..

**Comment by Haris1977** [comment]
Well it works as expected. The problem is when you exit the game, it hangs on the Gamestream image:(
