### ISSUE TITLE
mDNS discovery

### ISSUE THREAD

**Issue by substring** [irtimmer/moonlight-embedded#267]
Hi,

on the main page, it is said "Use mDNS to scan for compatible GeForce Experience (GFE) machines on the network"

How does it work from command line ? Running `moonlight pair` just freezes, and I see no other option to discover GFE servers

**Comment by Haris1977** [comment]
Does

moonlight pair IP_OF_PC work?

**Comment by substring** [comment]
Yes it does ! I expected something more like android moonlight : an option that lists available GFE servers. At least that's how i understand the text i quoted

**Comment by Haris1977** [comment]
Good to hear it works. Just a question though: Do you have any fps drops with your games? What is your host pc? I have opened an issue here https://github.com/irtimmer/moonlight-embedded/issues/252 and i am gathering some thoughts..

**Comment by substring** [comment]
i'll answer on your issue not to pollute this one

**Comment by irtimmer** [comment]
Without specifying the ip adres Moonlight Embedded use the first discovered computer. Too ensure discovering is working the Avahi daemon needs to be running.
