### ISSUE TITLE
Two controllers input (not) working?

### ISSUE THREAD

**Issue by Haris1977** [irtimmer/moonlight-embedded#269]
I use the command:

moonlight stream -mapping xbox.map -input /dev/input/event2 -mapping logitech.map -input /dev/input/event3 -input /dev/input/event0 -input /dev/input/event1 192.168.1.109  (events0 and 1 are my keyboard/mouse wireless combo)

Inside steam i can use both controllers, but inside games (e.g Nba2k10, pes09, pes14) only one controller and keyboard are present. Especially in games with individual control settings (like pro evolution soccer games - through settings.exe file) my logitech gamepad is NOT DETECTED as input!!

Strange thing is that in Ultra SFIV both controllers work (this game doesn't have individual settings exe though)!!

And yes..i used the same 2 controllers (xbox, logitech) to play NBA locally (through steam and stand alone) and both 2 controllers are detected! So.. Is this a known bug???

**Comment by 3djake** [comment]
Yeah, I am having issues with it too, how ever I cannot even use steam big picture mode for some reason. 
It used to work with one controller, I just got a second for some multiplayer games but I have not used moonlight in a few months and cannot remember how I got the controller working from looking at history.

I use 2 Wireless Logitech F710's and xbian. My issue is more likely PEBCAK but any advice on getting them working would be appreciated.

`sudo xboxdrv -i 0 --silent & sudo xboxdrv -i 1 --silent & moonlight stream -mapping testx -input /dev/input/event0 -mapping testx -input /dev/input/event1 -app Steam 10.0.0.30`

**Comment by RikJm** [comment]
Check if after you've clicked the controller icon in big picture (from your computer using a mouse) the controllers work again, I've been having this issue lately and "waking it up" from my pc seems to work.

Like you I had them working great on an earlier build but now it doesn't seem to pick them to be the default input for some reason.
