### ISSUE TITLE
CMake error Arch Linux

### ISSUE THREAD

**Issue by H3llsing** [irtimmer/moonlight-embedded#273]
Running on a rpi 2 Arch linux.
After installing all dependencies from wiki, i got this error during `cmake ../` command

`CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".    CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
`

do i have to set an environment variable or something similar ? 

ok i figured out, that i had to install also the package `make` 
now i got another error:

cmake ../
-- The C compiler identification is GNU 5.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ALSA: /usr/lib/libasound.so (found version "1.1.0")
-- Found Opus: /usr/lib/libopus.so
-- Found Broadcom: /opt/vc/include
-- Found Freescale: /opt/fsl/include
-- Found CEC: /usr/include (Required is at least version "3.0")
CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.4/Modules/FindPkgConfig.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/h3llsing/downloads/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".

after installing the package `pkg-config` i was able to start the make progress
next error:

`Scanning dependencies of target moonlight-imx
[ 88%] Building C object CMakeFiles/moonlight-imx.dir/src/video/imx.c.o
/home/h3llsing/downloads/moonlight-embedded/src/video/imx.c:27:21: schwerwiegender Fehler: libv4l2.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.`

after installing the package `libv4l` i was able to complete the make.

For all others in Short:
install also following packages:
`pacman -S make pkg-config libv4l`

**Comment by H3llsing** [comment]
Now i get an error when i try to run moonlight:
`moonlight: symbol lookup error: moonlight: undefined symbol: LiInitializeStreamConfiguration`

**Comment by Tunalord** [comment]
thanks for this.
