### ISSUE TITLE
Not Streaming  stuck on RTSP handshake

### ISSUE THREAD

**Issue by Athanaetos** [irtimmer/moonlight-embedded#279]
From the title, I can't seem to stream. It might be that my Geforce Experience is version 2.9+ or something else. Please help, I really want to try this.

**Comment by HarryLovesCode** [comment]
@Athanaetos Currently I'm on the Geforce Experience beta and I'm not having any hiccups. However, I encountered a similar issue when using a Xbox 360 controller with XPad. Black listing XPad and switching to XboxDrv fixed the problem, but I'm not sure if that is relevant to your issue.

**Comment by irtimmer** [comment]
Duplicate of #274
