### ISSUE TITLE
Xbox360 Rumble not working

### ISSUE THREAD

**Issue by thesymbol** [irtimmer/moonlight-embedded#285]
I have tested with xboxdrv --force-feedback but still dont get rumble to work, i can test the rumble feature of xboxdrv with --test-rumble and i can press left/right triggers to activate it.
But during game play i still do not get the rumble to work.

Is there any solution to this?

**Comment by cgutman** [comment]
The GameStream protocol doesn't currently support rumble.

**Comment by thesymbol** [comment]
Ah okay, well then i just have to wait :+1:
