### ISSUE TITLE
Analogue triggers ps3 controller

### ISSUE THREAD

**Issue by Tuxliri** [irtimmer/moonlight-embedded#287]
Hi, i use moonlight to stream driving games such as GRID autosport and they are playable but I suggest you to enable the analogue triggers otherwise the configuration isn't really optimal!

**Comment by irtimmer** [comment]
Please provide your own mapping file with anaolgue triggers so this could be added to the default mapping.

**Comment by sympoz** [comment]
set "enable_sbuttons" to 1 in /var/lib/sixad/default then run control mapping. But there is a problem with with analog triggers [issue #218](https://github.com/irtimmer/moonlight-embedded/issues/218)
