### ISSUE TITLE
NvStreamUserAgent.exe crashes with new http pairing

### ISSUE THREAD

**Issue by AreaScout** [irtimmer/moonlight-embedded#295]
When pairing with latest revision ( http pairing ) NvStreamUserAgent.exe crashes, so pairing never works 

Machine:
Windows 10 64bit
GeForce TI750
GeForce Experience 2.10.0 Beta + 361.43

**Comment by cgutman** [comment]
Can you upload the contents of your "C:\ProgramData\NVIDIA Corporation" folder? ProgramData is a hidden folder BTW.

**Comment by AreaScout** [comment]
Here you are, i always have to restart 'NVIDIA Streamer Service' that GFE 2.10 accepts connections and if it accepts connections and i start streaming, the GamesStreaming background app ( black GameStreaming screen ) is not starting, it only starts when i manually start 'nvstreamer.exe -sci -shield' then it kills that task, starts it's own nvstreamer.exe and starts the background app ( black GameStreaming screen ) and finally starts the game.    

http://www.areascout.at/GeForce%20Experience.zip

p.s.: i had to pair with an older version of moonlight

**Comment by AreaScout** [comment]
Here is a new Log with 3 pairing attempts at the end of the file, i hope GfeClientLog is enough 

http://www.areascout.at/GfeClientLog.zip

**Comment by AreaScout** [comment]
NVIDIA support team helped me to track down my connection problems, also the crash when pairing was caused by this, it was a conflict with 3rd party software ( Kaspersky Anti Virus )

Thanks for investigating

**Comment by AreaScout** [comment]
Issue still exists, while my connection problems are gone now it seem's that pairing still crashes NvStreamUserAgent.exe, i had i working once :(

**Comment by AreaScout** [comment]
I can confirm that this fixes pairing

thank you ! :dancer:

RG
