### ISSUE TITLE
Arch Repository not up to date

### ISSUE THREAD

**Issue by aPollO2k** [irtimmer/moonlight-embedded#306]
The Arch Package Repository is not up to date.

The version provided there is 2.1.1. Can you pls update it to the latest release 2.1.2 ? The repository is useless if i have to update and compile by myself to get the latest version.

I use Arch cause it runs faster then debian. Maybe the most people dont use it cause the are to lazy to try it out. But for me it works better.

**Comment by irtimmer** [comment]
The Arch repository have been updated.

**Comment by aPollO2k** [comment]
thanks a lot. but it's just updated for armv6 not for armv7 :)

**Comment by aPollO2k** [comment]
Thanks a lot now all works very fine. Very great work @irtimmer
