### ISSUE TITLE
Sound on both host and client

### ISSUE THREAD

**Issue by havnar** [irtimmer/moonlight-embedded#308]
When I stream content to my client it picks up the sound, but there is no longer sound on my host device. Is this by design or a setting? 
I could make a wiki entry if this is a setting that's unclear to me, otherwise could this be seen as a feature request?

**Comment by cgutman** [comment]
There is a flag for this: -localaudio

**Comment by havnar** [comment]
that didn't do anything for me the last time I've checked.
