### ISSUE TITLE
Pairing issue!

### ISSUE THREAD

**Issue by ImSAMazing** [irtimmer/moonlight-embedded#312]
Hey guys,

I have the following issue: 
I use the command ' moonlight pair IP'  on my raspberry pi 2b, and it says: type the following pin on the target pc, I did that, and it said: succesfully paired.
Then I type: ' moonlight stream -720 -30fps -app portal2' , and now it says: ' you must pair with the pc first' !?!? What do I need to do?

**Comment by dead** [comment]
Try: `moonlight stream -720 -30fps -app portal2 IP`

**Comment by irtimmer** [comment]
Pairing issues should be resolved with latest release.
