### ISSUE TITLE
Failed to pair to server: HTTP response code said error

### ISSUE THREAD

**Issue by wozzo** [irtimmer/moonlight-embedded#323]
When I attempt to pair I get the pin code, switch to GEF server and type it in to the pop up. Click Connect, back to the Pi and it says "Failed to pair to server: HTTP response code said error"

I'm using GEF 2.10.2.40 and have an Nvidia 970M.
For moonlight I have a Pi B+ running Jessie

**Comment by wozzo** [comment]
Just to be really confusing if I don't enter the pin and hit decline it now says successfully paired. Either way if I then try moonlight list IP I get a "You must pair with the PC first" message

**Comment by aikoncwd** [comment]
I have exactly the same issue here #231, but @irtimmer closed the issue :disappointed:

**Comment by wozzo** [comment]
Agreed. Definitely the same issue, and I've never had a beta version of GFE installed and have driver 361.91

**Comment by irtimmer** [comment]
Duplicate of #321

**Comment by wozzo** [comment]
Which also doesn't appear to be resolved? Can you explain the resolution if closing?

**Comment by wozzo** [comment]
What's the resolution please? @irtimmer

**Comment by cgutman** [comment]
@wozzo #324 describes the task of actually releasing the fixed build to package repositories.
