### ISSUE TITLE
Cant install Moonlight

### ISSUE THREAD

**Issue by BuzzKilll** [irtimmer/moonlight-embedded#326]
Hi, when i attempt to install moonlight, i get this error while running the command sudo apt-get install moonlight-embedded on my raspberrypi this error comes up, `sudo apt-get install moonlight-embedded
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  moonlight-embedded
0 upgraded, 1 newly installed, 0 to remove and 75 not upgraded.
Need to get 106 kB of archives.
After this operation, 289 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  moonlight-embedded
Install these packages without verification [y/N]? y
Err http://archive.itimmer.nl/raspbian/moonlight/ wheezy/main moonlight-embedded armhf 2.1.3-1wheezy1
  404  Not Found
Failed to fetch http://archive.itimmer.nl/raspbian/moonlight/pool/main/m/moonlight-embedded/moonlight-embedded_2.1.3-1wheezy1_armhf.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by dead** [comment]
Try update the repositories before.
`sudo apt-get update`
then
`sudo apt-get install moonlight-embedded`

**Comment by BuzzKilll** [comment]
I did, still isnt working.

**Comment by dead** [comment]
Well, then install the deb from: http://archive.itimmer.nl/raspbian/moonlight/pool/main/m/moonlight-embedded/moonlight-embedded_2.1.4-1wheezy1_armhf.deb

**Comment by BuzzKilll** [comment]
Well, not so surprised that worked Thanks for the great help
