### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by BuzzKilll** [irtimmer/moonlight-embedded#327]
When i  stream, i get video but no audio, i uncommented hdmi_drive=2 in /boot/config.txt/ anyway, im using hdmi and wifi, no ethernet sadly? any help please?

**Comment by Unknownforce351** [comment]
Try adding dtparam=audio=on to /boot/config.txt

**Comment by BuzzKilll** [comment]
Didnt work

**Comment by KWottrich** [comment]
Have you tried streaming different games?  I was getting no sound when I tried to stream a game using the Dolphin emulator, but sound worked when I tried a different game.  (The solution for Dolphin audio, if it matters, was to switch to OpenAL for sound.)

**Comment by dead** [comment]
You need provide more info...
What command line are you using to run the moonlight?
It is a raspberry pi? 1? 2? What distro?
Are you using an external audio?
What audio backend are you using?

Anyway, take a look a this https://github.com/dead/moonlight-openelec-rpi2/issues/6#issuecomment-192888433 maybe it could help you.

**Comment by BuzzKilll** [comment]
Hi, even the default moonlight stream 192.168.1.2 dosent give out any sound, raspberry pi B+, raspian,and using hdmi and tv speakers, im using a custom app in gamestream which is my desktop

**Comment by Unknownforce351** [comment]
Let's start from ground zero... Do you get audio from other applications on the Pi?  Not sure what else you might have on your Pi, but does anything else output sound?

Try doing this from the terminal:  speaker-test -c2

Getting sound from this?

**Comment by BuzzKilll** [comment]
Yep

**Comment by Unknownforce351** [comment]
No errors during compile, correct?  Do you hear the sound from the host computer while streaming?

**Comment by BuzzKilll** [comment]
Yeah i do, no errors

**Comment by Unknownforce351** [comment]
That's not working as expected.  During stream, audio should be redirected to client, not playing on Host at all.  Try using this option -audio sysdefault

Also, post the output from this command (lowercase L):
`aplay -l`
and from this one as well (uppercase L):
`aplay -L`

**Comment by BuzzKilll** [comment]
-adio sysdeafult dosent work : http://pastebin.com/V5JFVg8A

**Comment by Unknownforce351** [comment]
how about this output:
`moonlight list`

And what game(s) have you tested with?

**Comment by BuzzKilll** [comment]
I cant play any games, my geforce experience just wont update, just gives an error that it cannot connect to nvidea

**Comment by Unknownforce351** [comment]
You said you get video but no audio... I'm confused at the problem here...

**Comment by BuzzKilll** [comment]
no audio. thats all, i can stream my desktop but no games.

**Comment by BuzzKilll** [comment]
i get no audio via steam big picture or via desktop

**Comment by Unknownforce351** [comment]
What version of Geforce experience are you running?

**Comment by BuzzKilll** [comment]
v2.1.5.0

**Comment by Unknownforce351** [comment]
I'm surprised it does anything at all, you need to update this.  http://www.geforce.com/geforce-experience/download

**Comment by Unknownforce351** [comment]
And even update the Video drivers probably too... http://www.nvidia.com/Download/index.aspx?lang=en-us

**Comment by BuzzKilll** [comment]
I wont be able to reply in about 20 mins or so, going out to a business dinner

**Comment by BuzzKilll** [comment]
but ill download them while im gone! :D thanks so far for the help

**Comment by BuzzKilll** [comment]
GeForce experience Works!, im updating drivers atm! Thanks ill get back to you soon!

**Comment by BuzzKilll** [comment]
IT WORKS, IT WAS MY AUDIO DRIVER!  thanks again! bye bye now!
