### ISSUE TITLE
No keyboard and mouse when using -input command line switch 

### ISSUE THREAD

**Issue by substring** [irtimmer/moonlight-embedded#342]
Please provide the following info.

**_NVidia Geforce Experience version:_** 2.10.4
**Moonlight Embedded version:** 2.1.4
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._ [Recalbox](http://www.recalbox.com) on Pi

**Output of Moonlight Embedded:** don't have it at hand for now

**What is the expected result?**
When adding -input and -map for specific pads configuration, the keyboard and mouse should be added anyway

**What happens instead of that?**
the keyboard and mouse won't be added if a -input is passed as a moonlight argument

**Comment by wouterverduin** [comment]
How do you properly pass an -input signal?

**Comment by irtimmer** [comment]
You have to separately provide -input options for the mouse and keyboard.
