### ISSUE TITLE
Sticky button down problem

### ISSUE THREAD

**Issue by wouterverduin** [irtimmer/moonlight-embedded#346]
Hi there all!

I just did a clean install off moonlight embedded on my raspbian RPi2. Pairing and streaming works like a charm. However i run into the following problem:

It seems like the button down keeps being pressed infinitly. I also tried to unplug my USB3 controller and Keyboard from my RPi2 without succes. Is there a way to fix this issue?

I was thinking maybe selecting a -device would work? I would like to select my USB3 controller. How do i properly select it with -device?

**Comment by irtimmer** [comment]
Duplicate of #264
