### ISSUE TITLE
Loss Stats: Transaction failed: 11

### ISSUE THREAD

**Issue by theFisher86** [irtimmer/moonlight-embedded#362]
Please provide the following info.

**GFE 2.11.2.67**
**Moonlight Embedded version: 2.2.0**
**Moonlight Embedded running on:** Raspberry Pi

**Output of Moonlight Embedded:** 
```
...
Starting input stream...done
Control Stream received disconnect event
Loss Stats: Transaction failed: 11
```

This is happening everytime I try to stream anything...

**Comment by cgutman** [comment]
Can you upload the contents of your C:\ProgramData\NVIDIA Corporation\NvStream folder somewhere? Note that C:\ProgramData is a hidden folder.

**Comment by theFisher86** [comment]
Here's the current log

http://pastebin.com/PVLcfT4K

**Comment by cgutman** [comment]
#9(E)[2016-04-11 20:51:19,540]{000001F8} Failed to create FBC. Another instance exists and concurrent capture is not supported.

Do you have ShadowPlay turned on or some other software that would use hardware encoder and display capture?

**Comment by theFisher86** [comment]
The newest version of GFE doesn't have ShadowPlay however this got me to thinking and I uninstalled KinoConsole and it fixed the problem.  KinoConsole is a program that also streams your desktop.  For anyone else who comes across this issue make sure you uninstall or disable any program that allows remote desktops or streaming.  I can confirm TeamViewer does not cause any issues.  Scan your Task Manager and processes and Services to see things that are currently running.

**Comment by herobank110** [comment]
What worked for me was turning on privacy control in the share option of GeForce Experience as this is constantly recording your desktop.

**Comment by acid8x** [comment]
Same problem here, disconnecting itsel after +/- 1min. The only way I found to fix that was to set a lower bitrate. Default was 10000kbps, I set it to 5000
