### ISSUE TITLE
Downscaled/Not full screen (RPI3)

### ISSUE THREAD

**Issue by takkwin** [irtimmer/moonlight-embedded#378]
Hi,

**_NVidia Geforce Experience version:_** 2.11.3.5
**Moonlight Embedded version:** 2.2.1-1jessie1
**Moonlight Embedded running on:** RPI3

I have a problem with Moonlight displaying on my TV where the steam overlay/games are squeezed into a narrower resolution as shown below:

![img_20160529_124737](https://cloud.githubusercontent.com/assets/19706912/15742148/ccb73366-28ef-11e6-8a2b-42f6f73e0505.jpg)

I tried:
moonlight stream X.X.X.X
moonlight stream -720 X.X.X.X
moonlight stream -1080 X.X.X.X
Steam: Changed host and client resolutions in steam in-home streaming settings
Steam: Display target resolution to 1080p
Steam: Interface to windowed mode
Windows: Upsampling resolution to 1080p through Nvidia

The console displays:
![image](https://cloud.githubusercontent.com/assets/19706912/15742516/00228898-28f2-11e6-9d7c-9a77c9acef71.png)

Any help would be appreciated,
Thanks!

**Comment by TylerBre** [comment]
Well for one, I don't boot into the desktop enviroment, so maybe try that? Perhaps that is making some assumption about the native resolution for you? 

Do other games work for you?

Sidenote - how'd you get rocket league to work? I just get a white screen with controls + audio.
