### ISSUE TITLE
App doens't launch

### ISSUE THREAD

**Issue by kristijanH** [irtimmer/moonlight-embedded#389]
NVidia Geforce Experience version: 2.11.4.0
Moonlight Embedded version: latest version (installed 21/6/2016)
Moonlight Embedded running on: Raspbbery Pi 2
Output of Moonlight Embedded: not sure

OS: OSMC May 2016 2016.05-1 (openelec version jessie)

Moonlight does not start. I tried the Chrome version and it works so the problem is on my Rasbbery device and not my PC.

I installed the jessie build of moonlight without any problems and paired it with my PC but when I try to start the app I get a messege:

Moonlight Embedded 2.2. (EMBEDDED;PI)
Too many options: No such file or directory

**Comment by 7hunderbug** [comment]
What command line are you using to launch moonlight?

**Comment by kristijanH** [comment]
Normaly "moonlight streaming [] X.X.X.X". I also tried "sudo ..." with no effect. Tried also "moonlight streaming -app steam X.X.X.X".

I am using "putty" to input commands if that makes any difference.

**Comment by 7hunderbug** [comment]
Your syntax is incorrect. The correct syntax is:

moonlight stream X.X.X.X

I don't know where you got "streaming" from or "[]"

**Comment by kristijanH** [comment]
Now it works! I got the instruction form here:

http://www.howtogeek.com/220969/turn-a-raspberry-pi-into-a-steam-machine-with-moonlight/

I gues the author missused the last command. Everything else was spot on.

Thank you for your time.
