### ISSUE TITLE
EVIOCGRAB failed with error 22 

### ISSUE THREAD

**Issue by firepro20** [irtimmer/moonlight-embedded#391]
**_NVidia Geforce Experience version:_** 2.11.4.0
**Moonlight Embedded version:** 2.2.0
**Moonlight Embedded running on:** Raspberry Pi 3

**Output of Moonlight Embedded:**

Moonlight Embedded 2.2.0 (EMBEDDED;PULSE;PI)
Connect to 192.168.0.13...
NVIDIA GeForce GTX 970, GFE 2.11.4.0 (protocol version 7)
Add input /dev/input/js0 (mapping xbox.map)...
Stream 1920 x 1080, 60 fps, 20000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
EVIOCGRAB failed with error 22
libevdev error in libevdev_next_event: BUG: device not initialized. call libevdev_set_fd() first
Error: Bad file descriptor

**What is the expected result?**
Stream with mapped Dualshock 2 controller

**What happens instead of that?**

Crashes

**Comment by irtimmer** [comment]
Joystick interface is not supported. You can only use /dev/event*

_p.s. can you stop issuing duplicate bugs and non bugs?_
