### ISSUE TITLE
moonlight streaming issue

### ISSUE THREAD

**Issue by elanrad1** [irtimmer/moonlight-embedded#403]
**_NVidia Geforce Experience version:**
 2.11.4.0 (Latest version to this date 22/8/16).
**Moonlight Embedded version:**
V4.7 (Latest version to this date 22/8/16).
**Moonlight Embedded running on:** 
Windows 10 pro desktop
CPU: i7 4790k
GPU: Gtx 980 
RAM: 16 GB  
**Output of Moonlight Embedded:**
 An android phone - Samsung Galaxy S7.

**What is the expected result?**
 I'm trying to make it work over the internet away from home using ports. I've forwarded all of the ports that were listed on the Nvidia website.
**What happens instead of that?**
It is seeing my computer through the ports that I've opened BUT when I tap on my PC icon and after that I tap on the game that  I want to stream from my computer to my phone it does enter the game (i can see it on my pc) but after it writes on the phone "starting steam(for example)" then it writes "starting RTSP handshake" and then It loads a sec and writes "Connection Error , failed to start RTSP handshake". 
Please help me

**Comment by irtimmer** [comment]
You are not using Moonlight Embedded
