### ISSUE TITLE
Desktop Streaming; video overlay

### ISSUE THREAD

**Issue by Donalitu** [irtimmer/moonlight-embedded#406]
GFE:2.11.4
ML-E:2.2.0
RPI2 RASPBIAN JESSIE

I'm using Moonlight to mirror my computer to a projector in my livingroom and take to friends houses to play remotely. Everything on my desktop works except for one; flash full screen overlays... watching YouTube full screen the video will freeze while audio continues, using Plex or Netflix through Chrome yields the same results... the full screen video overlay freezes after a short time... Netflix app terminates connection but, I'm guessing it's using some of the same ports so, I watch through Chrome.

**Comment by irtimmer** [comment]
GameStream doesn't support video overlays
