### ISSUE TITLE
Resolution jumping / screen offsetting

### ISSUE THREAD

**Issue by forteh** [irtimmer/moonlight-embedded#407]
BIt of an odd one this and apologies if its a repeat of an existing issue, had a brief scan of open issues but didnt see the same come up.    Im not sure when this has started to happen as Ive not had much time recently to use moonlight/play games.

Streaming mtsc.exe works fine, load up steam as normal and play everything as I would expect to using a steam controller connected directly to the host PC (I have KBM connect to rpi as well), however every so often the screen gets a bit messed up and appears to stretch downwards a number of pixels; its enough to hide the windows task bar entirely when viewing the desktop. It becomes somewhat annoying in game because it often causes portions of the HUD to be hidden and distorts the view on screen.  The corruption usually last 10-30 seconds or so and seems to happen randomly, after which it will go back to the correct display.

Im running latest version of moonlight and gfe, the only change I can think of is that the rpi is now running 720p raspbian desktop and the host pc is running 1080p, I used to run the rpi at 1080p but found it far more useable on the larger tv at 720p.

My command line is: -
moonlight stream -app win -bitrate 6000 -1080 -60fps 192.168.1.6

I get not errors in the terminal window on the rpi, infact as I type this I cannot see my taskbar!

**Comment by irtimmer** [comment]
This issue don't seem to be reproducible so please check the new version to see if your issue is resolved.
