### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ronyn77** [irtimmer/moonlight-embedded#408]
Hello,

This is my configuration : 

Server/Streaming machine
Gtx 980m
I7-4860HQ
16 GB RAM
Driver nvidia 372.70 ver with last GFE
Windows 10 pro
Xbox360 receiver + xbox360 wireless gamepad
Host/Client machine
Gtx 840m
I3-4030U
8 GB RAM
Driver nvidia 372.70 ver with last GFE
WINDOWS 8.1 pro
Xbox360 receiver + xbox360 wireless gamepad
Moonlight Chrome v.0.5 Alpha 5 (java version is too  slow)

The server is connected directly to the router with gigabit lan cable connection.
The client is connected by Wi-Fi AC to the same router.

In general the streaming quality is good at 1080p60hz. There is no input lag. It is like playing directly on the server machine.
I have configured  the server machine to accept Remote Desktop through Gfe.
In general i made the streaming connection by firstly access as remote desktop and afterwards i start the desidered game. i prefer this option because in most of the cases if i choose directly the game it returns to me an error : stream://rungameid/xxxxxx application not found. How can I fix this issue?
Anyway, this is not my main issue. The big problem are the controllers.
If i try to play any games on the client machine, depends on the game(like killer instict), the gamepad on the client machine is not mapped and i can only use the gamepad connected to the server machine. Other games like Fifa 15, can be played using the gamepad connected to the client machine.
What I would like to achieve is to make a local co-op playing on two separate pcs. E.g. Start killer instict or whatever with local multiplayer (versus mode) on the server with the first controller mapped and connected on the server machine for player one, use moonlight to stream on the client pc and map player two (or more if the game supports it) on the gamepad connected on the client machine.
Is there any way to do it?

**Comment by irtimmer** [comment]
Moonlight Chrome isn't Moonlight Embedded

**Comment by ronyn77** [comment]
Hello Irtimmer,

Why do you close my post?

I am new on this forum, probably i have made some mistakes..i do not know...
Could you explain me?

Thank you in advance,

Robert

Inviato da iPad
