### ISSUE TITLE
Controller BUG

### ISSUE THREAD

**Issue by mclucario** [irtimmer/moonlight-embedded#409]
Please provide the following info.

**_NVidia Geforce Experience version:_** _2.11.4.0_
**Moonlight Embedded version:** _2.2.0_
**Moonlight Embedded running on:** _Raspberry Pi_
**Additional Info:** _Running on RetroPie with a PS3 Controller on Cable without bluetooth connection. Also The PS3 driver is not installed but the controller works in emulationstation._
**Output of Moonlight Embedded:**

---

**What is the expected result?**

The Button should be stop doing its thing when I dont press it anymore.
(Controller works normal on PS3)

**What happens instead of that?**

The button keeps being pressed even tho im not pressing it. It keeps going up and right.

**Comment by irtimmer** [comment]
Please run evtest and press the mall-functioning button and upload the output so the problem can be debugged.
