### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by raynetec** [irtimmer/moonlight-embedded#411]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.0.5.22
**Moonlight Embedded version:** 2.2.0
**Moonlight Embedded running on:** LibreELEC x86_64

**Output of Moonlight Embedded:**
moonlight stream -audio hw:0,7 192.168.1.10
Moonlight Embedded 2.2.0 (SDL;VDPAU;PULSE;CEC)
Connect to 192.168.1.10...
NVIDIA GeForce GTX 1070, GFE 3.0.5.22 (protocol version 7)
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Decode failed - Invalid data found when processing input
Decode failed - Invalid data found when processing input
Control stream received disconnect event
Loss Stats: Transaction failed: 11
Segmentation fault (core dumped)

**What is the expected result?**
I expected to hear audio, like on my RaspberryPi 3.
**What happens instead of that?**
I get video and can play games but i don't get an audio output. Tested with Steam and several games.

I checked aplay-l to get the right audio device and get an audio output with "aplay -D hw:0,7 test.wav".

//edit maybe dmesg helps to track down the issue:
moonlight[24952]: segfault at 2d0 ip 00007f2b9d85d250 sp 00007f2b81ffae48 error 4 in libpthread-2.23.so[7f2b9d84f000+18000]

**Comment by goodpunk6** [comment]
I'm sorry friend, but what did you do to resolve the issue?
