### ISSUE TITLE
Collection of issues I've found with GFE 3

### ISSUE THREAD

**Issue by DarioRomano** [irtimmer/moonlight-embedded#413]
Please provide the following info.

*__NVidia Geforce Experience version: 3.0.5.22 *_
*_Moonlight Embedded version: 2.2.0 *_
*_Moonlight Embedded running on: Raspberry Pi 3 B *_

I'm putting a few issues I've experienced with the new major release of Geforce Experience in here:
1.  Issues in recognizing controllers attached to the host machine.
   I usually attach the controllers I use to my host machine, since it's nearer to the couch. I applied the dxinput.dll fix with the new version, and the controller does work in SOME games, but the majority of games just don't recognize the controller within the game. Steam with the controller works. 
   I've tested a normal Xbox 360 controller and a DS4 Controller hooked up wirelessly with the DS4Windows software.
   Both controllers "worked" equally.
   A game that worked was "Enter the Gungeon" whereas games that didn't work were "Stardew Valley" and "Geometry Wars 3".
   Not sure if this issue is related to the new GFE version, or a bug in combination with moonlight embedded.
2. There sometimes appears an issue when connecting which says "RTSP handshake failed". A reboot of the Pi and the PC makes the whole thing work again. Not sure what could be causing this problem.

For now I'm just using the older version of GFE to have everything working, but I'd love to continue using this software on the new major release of GFE, so I thought I just mention what I've found.

Cheers.

**Comment by irtimmer** [comment]
As far as known these are issues from Geforce Experience which can't be fixed by changes in Moonlight Embedded.
