### ISSUE TITLE
Screen "Gamestream" when i close a game, i can't close it

### ISSUE THREAD

**Issue by Kheiryk** [irtimmer/moonlight-embedded#418]
Hi
I've a screen Gamestream when i close a game, and i can't change the game, because i am blocked on this screen and i can't close it since raspbian, on windows 7 :
![screen](https://cloud.githubusercontent.com/assets/16276098/19197008/0ed9bd5a-8cb8-11e6-9b80-29b6dca855b7.JPG)
i must to go on Windows and close this screen for play at another game ... :/
can you help me please
thanks

**Comment by Kheiryk** [comment]
When i play with Steam bic picture, this screen stay behind, and i can play to a an other game !

**Comment by irtimmer** [comment]
This bug looks like an issue in Gefore Experience and not in Moonlight Embedded
