### ISSUE TITLE
Wired pad xbox360 - little problem with the map buttons

### ISSUE THREAD

**Issue by Kheiryk** [irtimmer/moonlight-embedded#419]
Hi all,
When i use my xbox.map file, the buttons RT / LT not working
When i don't use my xbox.map (when i start a game in the bash file without -mapping, xboxdrv installed), X and Y buttons are inverse but LT/RT works !

Do you know how i can resolve it please ?
thanks

xbox.map 

```
abs_x = 0
abs_y = 1
abs_z = 10
abs_rx = 3
abs_ry = 4
abs_rz = 9
abs_deadzone = 0
abs_dpad_x = 17
abs_dpad_y = 16
reverse_x = false
reverse_y = true
reverse_rx = false
reverse_ry = true
reverse_dpad_x = false
reverse_dpad_y = false
btn_east = 305
btn_south = 304
btn_north = 308
btn_west = 307
btn_select = 314
btn_start = 315
btn_mode = 316
btn_thumbl = 317
btn_thumbr = 318
btn_tl = 310
btn_tr = 311
btn_tl2 = 312
btn_tr2 = 313
btn_dpad_up = -1
btn_dpad_down = -1
btn_dpad_left = -1
btn_dpad_right = -1

```

in my rc.local file
`xboxdrv --trigger-as-button --id 0 --led 2 --deadzone 4000 --silent & sleep 1
`

With Steam or not steam, in Steam when i check the controller, i see just XINPUT controler x4

**Comment by CUD** [comment]
I'm having the same issue with the X and Y buttons being switched. I tried entering the inputs in reverse when prompted (X when prompted for Y and vice versa) but it still didn't work, strangely enough.

**Comment by Athou** [comment]
Had the same issue, I played a little bit with the mappings and I think I finally have something working for the wired xbox controller:

```
abs_x = 0
abs_y = 1
abs_z = 2
reverse_x = false
reverse_y = true
abs_rx = 3
abs_ry = 4
abs_rz = 5
reverse_rx = false
reverse_ry = true
abs_deadzone = 0
abs_dpad_x = 16
abs_dpad_y = 17
reverse_dpad_x = false
reverse_dpad_y = false
btn_north = 308
btn_east = 305
btn_south = 304
btn_west = 307
btn_select = 314
btn_start = 315
btn_mode = 316
btn_thumbl = 317
btn_thumbr = 318
btn_tl = 310
btn_tr = 311
btn_tl2 = -1
btn_tr2 = -1
btn_dpad_up = 546
btn_dpad_down = 547
btn_dpad_left = 544
btn_dpad_right = 545
```
