### ISSUE TITLE
Vita analog sticks

### ISSUE THREAD

**Issue by Armzeruel** [irtimmer/moonlight-embedded#421]
**_NVidia Geforce Experience version:_** 3.0.7
**Moonlight Embedded version:** 5 alpha
**Moonlight Embedded running on:** PSVITA
**Output of Moonlight Embedded:** analog stick dont work anywhere, specifically on pcsx2, x360ce, xinput test - all button register after pressing, sticks not, like they not exist.

**What is the expected result?** working analog vita sticks with pcsx2

**Comment by irtimmer** [comment]
Moonlight Embedded doesn't run on a PS Vita

**Comment by CvH** [comment]
you probably want this https://github.com/xyzz/vita-moonlight/
