### ISSUE TITLE
RTSP Failed to connect to UDP port 48010 failed:-1

### ISSUE THREAD

**Issue by blast1987** [irtimmer/moonlight-embedded#423]
Hello i am getting this error on GFE 3.0.7: RTSP Failed to connect to UDP port 48010 failed:-1

GFE version 3.0.7.34
moonlight embedded version 2.2.2
Device: Raspberry Pi 3

**Comment by georgcmef** [comment]
I get the same error, a workaround: reinstalling Geforce experience after every system POST works till the next POST.

**Comment by blast1987** [comment]
So does it mean i have to reinstall GFE after every reboot?

**Comment by raynetec** [comment]
There's a problem in the latest GFE 3.0.7.34. Try to lock and then unlock your system and see if that works for you.
Source: [GeForce Forum](https://forums.geforce.com/default/topic/970697/gamestream/373-06-driver-completely-broke-gamestream-error-8033020f-when-trying-to-launch-a-game-/post/4993302/#4993302)

**Comment by Gobol** [comment]
I got this error when I request incompatible resolution with my primary server display...
