### ISSUE TITLE
Cannot stream with 4G

### ISSUE THREAD

**Issue by vinilodeon** [irtimmer/moonlight-embedded#425]
Issue = https://www.youtube.com/watch?v=koou26fn5lA

Router = exposed host
local = works fine
GPU = Nvidia GTX 980 ti
Nvidia Geforce experience 3.0.7.34 (tried older version, no sucess)
Windows 10
Firewall and Antivirus deactivated

want to stream on my Nvidia k1 tablet

any ideas to fix the issue? 

Nvidia Corporation files: https://1drv.ms/u/s!AudJExOtNbK_gesloeaiRgCrGw6SXQ

Thanks

**Comment by irtimmer** [comment]
You aren't using Moonlight Embedded
