### ISSUE TITLE
Bluetooth headset

### ISSUE THREAD

**Issue by Pshlos** [irtimmer/moonlight-embedded#426]
I bought a bluetooth headset to wear so i can play while the general is sleeping. The headset connects to the rpi3 and works normally. When i connect to my pc useing moonlight the audio defaults to the hdmi.
I'm quite new to linux. i know that moonlight has a -audio modifier but i dont know what to type after it.
Thank you

**_NVidia Geforce Experience version:_30734**
**Moonlight Embedded running on:** _Raspberry Pi

**Comment by Pshlos** [comment]
Can anyone pls help

**Comment by irtimmer** [comment]
This isn't a Linux support forum...
