### ISSUE TITLE
provide apt signing key

### ISSUE THREAD

**Issue by dayne** [irtimmer/moonlight-embedded#428]
Just a poke to the package providers maintaining the apt repo to provide the signing key.

https://github.com/irtimmer/moonlight-embedded/wiki/Packages

Want to get rid of this warning by installing gpg key while setting up the apt repo:

```
WARNING: The following packages cannot be authenticated!
  moonlight-embedded
Install these packages without verification? [y/N] n
```

**Comment by irtimmer** [comment]
A GPG key is now available on http://archive.itimmer.nl/itimmer.gpg

**Comment by discordianfish** [comment]
@irtimmer Can you maybe move it somewhere where it's using https?
