### ISSUE TITLE
Raspberry Pi 3 and PC won't pair.  PC never shows PIN to enter.

### ISSUE THREAD

**Issue by goodpunk6** [irtimmer/moonlight-embedded#432]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.0.7.34
**Moonlight Embedded version:** 2.2.2
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._  Raspberry Pi 3

**Output of Moonlight Embedded:**  just says connecting and the IP address.  then it says it fails to pair

**What is the expected result?**  I expect my PC to prompt me to pair.  My PC is logged into Nvidia and ready to pair.

**What happens instead of that?**  Nothing.  I never get prompted for anything.

**Comment by wilkie1020** [comment]
Game streaming enabled in Geforce Experience?

**Comment by goodpunk6** [comment]
Yes it is enabled on the PC

**Comment by cgutman** [comment]
Try upgrading to GeForce Experience 3.1.0.52

**Comment by goodpunk6** [comment]
I will upgrade when I get home.  I'll report back then.

**Comment by goodpunk6** [comment]
I upgraded Geforce Experience!  It finally prompted me for the pin!  However, it won't start streaming.

**Comment by goodpunk6** [comment]
correction, i reran the command, it works!  yessssss!!!  i was streaming Gears of War 4!!!  I can't wait to give this as a gift for christmas!

**Comment by goodpunk6** [comment]
Ok, I still have a problem...no sound.  =( where are the logs?  I'd love to post/share them.
