### ISSUE TITLE
Can not compile Moonlight-embedded.

### ISSUE THREAD

**Issue by PhilippMeissner** [irtimmer/moonlight-embedded#433]
Please provide the following info.

**GFE 3.0.7.34 **
**Moonlight Embedded version:** 2.2.2 (Through `apt-get install moonlight`
**Moonlight Embedded running on:** _Raspberry Pi 2 with Raspbian_

**Output of Moonlight Embedded:**
```
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY) 
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY) 
-- Checking for module 'libevdev'
--   No package 'libevdev' found
CMake Error at /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:23 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/pi/moonlight-embedded/CMakeFiles/CMakeOutput.log".

```

**What is the expected result?** Should compile.

**What happens instead of that?** When inside `moonlight-embedded/build` when running `cmake ../` the error above pops up. I followed the guide from the wiki but can not seem to get this installed.

When trying to install `libevdev-dev` the following error pops up:
```
The following packages have unmet dependencies:
 libevdev-dev : Depends: libevdev2 (= 1.3+dfsg-1) but 1.4.6+dfsg-1 is to be installed
```

Unfortunately I can not upgrade `libevdev2` as it is the latest version.

**Comment by mitymarcus** [comment]
Try running
`apt-get update`
