### ISSUE TITLE
can't pair 2.2.2 with GFE 3.1.0.52

### ISSUE THREAD

**Issue by grgohr** [irtimmer/moonlight-embedded#435]
**GFE 3.1.0.52
Moonlight Embedded 2.2.2 (SDL;CEC) running on Odroid XU4**

**Output of Moonlight Embedded:**
```
# moonlight pair
Moonlight Embedded 2.2.2 (SDL;CEC)
Searching for server...
Connect to 192.168.0.2...
Generating certificate...done
Can't connect to server 192.168.0.2
```

**What is the expected result?**
Gamestream is on
http://127.0.0.1:47989/serverinfo?uniqueid=1234 gives a proper XML
the PIN should be requested in GFE

**What happens instead of that?**
=> the PIN request never shows under GFE
=> the keydir option is ignored, a folder "192.168.0.2" is automatically created instead (with usual key files inside despite the missing PIN request step)
=> nothing in GFE shows an existing shield peripheral

**Comment by grgohr** [comment]
better with the latest GFE update but still nowhere to input the PIN 

`# moonlight pair`
`Moonlight Embedded 2.2.2 (SDL;CEC)`
`Searching for server...`
`Connect to 192.168.0.2...`
`Generating certificate...done`
`NVIDIA GeForce GTX 970, GFE 3.1.0.52 (protocol version 7)`
`Please enter the following PIN on the target PC: 2136`
`Failed to pair to server: Pairing failed`

**Comment by romanovzky** [comment]
Luckier than me, mine doesn't even go through Connect to xxx.xxx.xxx.xxx

Any ideas?

**Comment by grgohr** [comment]
have you triggered the gamestream option in GFE prefs ?
is http://127.0.0.1:47989/serverinfo?uniqueid=1234 returning an XML ?

**Comment by romanovzky** [comment]
In this new GFE I can't seem to interact with any gamestream option. It just says "ready", but there's no switch or button. In GF2 there were options, list of paired devices, etc in this one is just another listing in the settings, but not interactive.

The second link does nothing, as clicked here. Should I change it to fit my own network IPs? I don't understand what that link should do...

**Comment by romanovzky** [comment]
This is what I see on the PC GFE

![GFE](http://i.imgur.com/vDVJdbr.png)

**Comment by cgutman** [comment]
There should be a SHIELD tab on the left side of the settings page. That's where you enable GameStream.

**Comment by romanovzky** [comment]
This is my settings, no SHIELD tab or option. Is this normal?

![Imgur](http://i.imgur.com/LcFfXrA.png)

**Comment by cgutman** [comment]
No, but you can try enabling "Allow experimental features", wait 5 minutes or so, then restart GeForce Experience and you should get an update. See if that update fixes your issue.

**Comment by grgohr** [comment]
and if not appearing you should uninstall/reinstall, the shield tab should appear on the screen.

now back to the original issue of the thread, any idea why the PIN popup does not show up while pairing ?

**Comment by grgohr** [comment]
mmh actually followed my own advice : uninstalled GFE, reinstalled.
now the popup appears when pairing.
GFE is pretty bugged when upgraded...

**Comment by romanovzky** [comment]
My issue was also solved, thanks guys!
