### ISSUE TITLE
Support for NextThing.co CHIP?

### ISSUE THREAD

**Issue by andreacampanella** [irtimmer/moonlight-embedded#439]
Sorry for the crude use of the Issue report, I tried to compile moonlight-embedded on the CHIP ( https://nextthing.co/pages/pocketchip ) the chip cpu is an Allwinner R8  ( http://linux-sunxi.org/R8 ) but the compilation ends, as expected with " No video output available " , any plan to port moonlight-embedded to this platform? I would be happy to be a tester if needed.

**Comment by irtimmer** [comment]
Duplicate of #249 as NextThing.co CHIP also looks to use CedarX for video decoding
