### ISSUE TITLE
Could not map buttons from dance mat 

### ISSUE THREAD

**Issue by juasker** [irtimmer/moonlight-embedded#441]
**_NVidia Geforce Experience version:_3.1.2.31 (protocol version 7)**
**Moonlight Embedded version:*2.2.2 (EMBEDDED;PI)*
**Moonlight Embedded running on:** _Raspberry Pi 2

**Output of Moonlight Embedded:**

**What is the expected result?**
Be able to play Stepmania(DDR) using dance mat connected to raspberry pi

**What happens instead of that?**
Hello. I have Rapsberry pi 2 with retripie + moonlight installed there.
When i user Xbox 360 controllers all works perfect, i be able to play pc games.
But suddenly i wanted to play Stepmania (Dance Dance Revolution) using dance mats.
The problem is when i try to do the mapping (moonlight map dance.map) moonlight does not recognize any buttons pressed. So inside stepmania i can't map any buttons(
The mats are working and be able to configure them in the Retropie system.

Any1 tried to do that trick?

**Comment by tapestreamer** [comment]
Try using [Antimicro] (https://github.com/AntiMicro/antimicro) for mapping/changing controller setup.
