### ISSUE TITLE
When using Moonlight on Raspberry Pi 2, Steam Big Picture is frozen

### ISSUE THREAD

**Issue by CassiusSaiz** [irtimmer/moonlight-embedded#442]
NVidia Geforce Experience version: 3.1.2.31, running on a GTX 1070

Moonlight Embedded version: 2.2.2

Moonlight Embedded running on: Raspberry Pi 2

Output of Moonlight Embedded: Black screen, when HDMI is unplugged from Raspberry Pi 2 and placed in host PC, and moved back the screen is frozen, and controller does nothing. Once a game is selected streaming then works on Raspberry Pi 2 client with wired Xbox 360 controller working as input. 

Expected Result: Steam Big Picture allowing Raspberry Pi 2 client to navigate interface and select game. 

What happens instead: Black screen, when HDMI is unplugged and plugged back in, screen is frozen. Once game is selected in Windows, streaming then works.

**Comment by tapestreamer** [comment]
I've had a similar issue. Try changing the resolution of the Pi and boot with a monitor/tv connected already.
Also a black screen when booting without a monitor on my Pi.

I had black screen in the following situation:
- Startup moonlight from Pi, connect monitor to Pi > black screen.
- Startup moonlight from Pi, re-connect monitor to Pi > black screen.
