### ISSUE TITLE
Compilation broken with libcec 4.0.0

### ISSUE THREAD

**Issue by lrusak** [irtimmer/moonlight-embedded#445]
Please provide the following info.

**_NVidia Geforce Experience version:_** N/A
**Moonlight Embedded version:** 2.2.2
**Moonlight Embedded running on:** N/A

**Output of Moonlight Embedded:**

Build log --> http://sprunge.us/LLhQ

**What is the expected result?**

That moonlight-embedded builds successfully

**What happens instead of that?**

moonlight-embedded fails to build

**Comment by irtimmer** [comment]
Fixed in  commit 90bfcdcc4da4178b0fd6c6013947006cd1c07377

**Comment by lrusak** [comment]
Thanks!
