### ISSUE TITLE
sudo cmake ../ not working

### ISSUE THREAD

**Issue by notJHNTR** [irtimmer/moonlight-embedded#455]
Hi I was trying to install Moonlight to my **Raspberry Pi 3(running Retropie)** and I was following these instructions _https://blog.jhot.me/guide-install-moonlight-on-raspbian-retropie-9d1318b8ddf8#.wu3eax42p_
Everything worked great until the command sudo cmake ../ came up and I run in some errors and I don't understand how I can fix it.

**NVidia Geforce Experience version:** 3.2.0.69 (not that it matters)
**Moonlight Embedded version:** 2.2.3
**Moonlight Embedded running on:** Raspberry Pi 3 (running Retropie)

**Output of Moonlight Embedded(Command line):** 
pi@retropie:~/moonlight-embedded-2.2.3/build $ sudo cmake ../
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY)
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
-- Checking for module 'vdpau'
--   No package 'vdpau' found
-- Checking for module 'libcec>=3.0.0'
)--
-- Checking for module 'libenet'
--   No package 'libenet' found
CMake Error at /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  libgamestream/CMakeLists.txt:8 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/pi/moonlight-embedded-2.2.3/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/moonlight-embedded-2.2.3/build/CMakeFiles/CMakeError.log".

**What is the expected result?** Should create a makefile

**What happens instead of that?** Errors occur saying there are files missing

**Comment by irtimmer** [comment]
https://github.com/irtimmer/moonlight-embedded/wiki/Compilation#debian-raspbian--osmc
