### ISSUE TITLE
Problems with spanish keyboard

### ISSUE THREAD

**Issue by Fransiro** [irtimmer/moonlight-embedded#461]
Raspberry pi 3 with raspbian (wheezy)
Moonlight embedded 2.2.2a
Geforce Experience 3.2.2.49

I have a spanish keyboard (logitech k400r) that runs good on rpi3 and on my pc but when i use it with moonlight-embedded the keyboard localized is in en_US i can't put "Ñ" character and other special keys are changed.

¿Moonlight-embedded support spanish keyboards?  ¿Can i map with a properties file my keyboard to use it?

Greetings

**Comment by irtimmer** [comment]
Duplicate of #55
