### ISSUE TITLE
Cannot connect to the server [name of the game I'm trying to stream]

### ISSUE THREAD

**Issue by outrunnerpt** [irtimmer/moonlight-embedded#462]
NVidia Geforce Experience version: 3.2.2.49
Moonlight Embedded version: the latest on the repo
Moonlight Embedded running on: Raspberry Pi3

Guys I'm having a problem. I installed Moonlight from the Repo on Raspbian Jessie, I paired with my PC without any problems, can get the list of games to stream but every time I try to start to stream a game Moonlight says it "cannot connect to the server [name of the game I'm trying to stream ]". 

I tried with ethernet conection and Wifi, I tried deactivating firewall and AV on PC, with no improvement, any ideas?

**Comment by Sardtok** [comment]
What command are you using to run moonlight? Sounds like you are invoking the command incorrectly. If you are trying to run a game, you should use `moonlight stream -app game` not `moonlight stream game`. The latter would try to stream Steam from the server with the hostname game.
