### ISSUE TITLE
Map Controller to key combo (escape)

### ISSUE THREAD

**Issue by galvatrondeva** [irtimmer/moonlight-embedded#463]
**_NVidia Geforce Experience version:_**  3.2.2.49
**Moonlight Embedded version:** 2.2.2
**Moonlight Embedded running on:** Pie3 - Retropie 4.1

I've added the front-end Launchbox (Big Box mode) to steam as a means to run higher demanding emulators through Retropie via moonlight-embedded. Ultimately this will turn into a hand held build. The streaming is amazing btw! 

What I'd like to do is add "a combination of keys" = "escape" on the keyboard in my moonlight controller.map.   But Im afraid i dont understand how to manipulate it with the nomenclature being a bit different on .map vs .cfg

btn_mode = abs_x = 0
abs_y = 1
abs_z = -1
reverse_x = false
reverse_y = true
abs_rx = 5
abs_ry = 2
abs_rz = -1
reverse_rx = false
reverse_ry = true
abs_deadzone = 30448
abs_dpad_x = 16
abs_dpad_y = 17
reverse_dpad_x = false
reverse_dpad_y = false
btn_north = 288
btn_east = 289
btn_south = 290
btn_west = 291
btn_select = 297
btn_start = 296
btn_mode = 300
btn_thumbl = 298
btn_thumbr = 299
btn_tl = 294
btn_tr = 295
btn_tl2 = 292
btn_tr2 = 293
btn_dpad_up = -1
btn_dpad_down = -1
btn_dpad_left = -1
btn_dpad_right = -1

What i think it might look like based of my controllers.cfg
input_start_btn = "296"
input_exit_emulator_btn = "296"
input_select_btn = "297"
input_enable_hotkey_btn = "297"

Is there a way to use this or something like it?

**Comment by irtimmer** [comment]
Controller input can't be mapped to keys. Your problem probably can be resolved by using a external program on the host converting controller input to keyboard input.
