### ISSUE TITLE
Unable to pair with GFE 3 and above

### ISSUE THREAD

**Issue by shandshellin** [irtimmer/moonlight-embedded#467]
Please provide the following info.

**Any version of GFE 3**
**2.2.3**
**Moonlight Embedded running on:** _Raspberry Pi 3
**Output of Moonlight Embedded:**

**Pairing with computer.**

**"error connecting to server" when running any version of GFE 3 i am unable to pair. If i downgrade GFE to v 2.11.4.0 it pairs and works great. This is running the most recent nvidia driver on a 660 gtx 2-way SLI. I have tested each version of Geforce Experience 3 up to the latest release and i just straight up cannot pair. I can Ping. Once i downgrade i can pair no problem.**

**Comment by irtimmer** [comment]
Don't forget to enable GameStream in GFE3. See https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide
