### ISSUE TITLE
Using Steam Controller with Moonlight + Pi?

### ISSUE THREAD

**Issue by Jbbrack03** [irtimmer/moonlight-embedded#470]
Just a quick question/issue. I've got Moonlight up and running with my Raspberry Pi which is compiled on the latest version of Raspbian Jessie. It works great over Ethernet with a Mouse/Keyboard. I'd like to use my Steam Controller to control things. I think that this might be currently possible with some emulation, but I need it to act like a Steam Controller. I have my Steam Controller mapped out in Steam to control several MMO games that I play. I'd love to play them in the Living Room with the Steam Controller. Is this currently possible? Can the Steam Controller be setup to be detected as a Steam Controller during In-Home Streaming?

**Comment by irtimmer** [comment]
No, all controllers will work like a NVidia Shield controller
