### ISSUE TITLE
Can't launch steam game through Moonlight

### ISSUE THREAD

**Issue by Bastbog** [irtimmer/moonlight-embedded#471]
Please provide the following info.

**_NVidia Geforce Experience version:_**3.3.0.95
**Moonlight Embedded running on:** Raspberry pi 3

I have an issue where i can't start any steam game.
Big picture boots up just fine, but any game just gets me a splash screen and back to big picture.

The weird thing is i can start watch dogs 2 through steam that goes through uplay.
Any ideas?

**Comment by irtimmer** [comment]
Duplicate of #394
