### ISSUE TITLE
No Steam GUI > GFE 2.11.40

### ISSUE THREAD

**Issue by noxx2015** [irtimmer/moonlight-embedded#472]
hello

moonlight works well with GFE 2.11.4.0, but
if i make a update, paring works, but Steam (Big Picture) doesnt start.

i see only my Server Desktop.
i try it with 
GFE 3.1.2.31
GFE 3.2.0.96
GFE 3.3.0.97

Firewall is off. 
Pairing works with all versions.
2.11 show Steam Big Picture
other show only Desktop

regard

**Comment by irtimmer** [comment]
This bug report looks like an issue in Steam or Geforce Experience and not in Moonlight Embedded.
