### ISSUE TITLE
steam steam://rungameid/

### ISSUE THREAD

**Issue by backstander** [irtimmer/moonlight-embedded#475]
**_NVidia Geforce Experience version: 3.3.0.95**
**Moonlight Embedded version: 2.2.2 (EMBEDDED;PI)**
**Moonlight Embedded running on: Raspberry Pi 3**

I've got everything else working great but is there a way to use the Run Game ID to launch a specific game through Steam using Moonlight Embedded?
Example for Half-Life 2:
`steam steam://rungameid/220`

I've tried running `moonlight stream -mapping controller.map -app "steam steam://rungameid/220" <ipaddress>` but it doesn't work and was wondering if someone knew of another way to accomplish this?

**Comment by irtimmer** [comment]
You can't start any executable on the host. Use `moonlight list <ipaddress>` to get a list of games which can be used in `moonlight stream -mapping controller.map -app "<gamename>" <ipaddress>`
