### ISSUE TITLE
Sound crash when streaming to Pi 3 (Witcher 3)

### ISSUE THREAD

**Issue by deimos2005** [irtimmer/moonlight-embedded#479]
**NVidia Geforce Experience version:** _3.4.0.70_
**Moonlight Embedded version:** _2.2.3_
**Moonlight Embedded running on:** _Raspberry Pi 3_

**What is the expected result?** _Normal streaming with good picture and sound._

**What happens instead of that?** _Video stream is well done, but sound is crash. Into Steam sound played normally._

**Comment by irtimmer** [comment]
Bug report is missing output of Moonlight Embedded
