### ISSUE TITLE
DualShock controller > Xbox icons ?

### ISSUE THREAD

**Issue by CorB3n** [irtimmer/moonlight-embedded#480]
Hello,

Like many I use Moonlight to stream my games on my Sony TV (Android). I've paired my PS4 controller to my TV and it works fine. However, the controls displayed in each of the games correspond to the Xbox keys (A, E etc.) and not to the PS4 DualShock controls. What is the solution to display the PS4 controls, a file to modify or do I have to memorize the controls of a controller I do not have: p ?

Thanks for helping !

**Comment by irtimmer** [comment]
The protocol don't support sending the type of the controller. Therefore all controllers will be seen as a NVidia Shield controller which is a Xbox like controller.
