### ISSUE TITLE
Problems with controller support

### ISSUE THREAD

**Issue by Donbarto** [irtimmer/moonlight-embedded#483]
hi i have some question. i was using moonlight before on my raspberry 3 with my controller xbox360 wireless connected to my computer.
it work great before i had rumble support and the buttons mostly setup itself.
since i have everything on new version its seems like moonlight interrupt that i dont have a control over computer if i start a game.
but when i connect my controller to raspberry it works.
but this mappings are sometimes pain in the ass i like the way over my computer more.
could i deactivate this controller support in moonlight that i just stream?

**Comment by irtimmer** [comment]
Possibility to disable input from Moonlight is documented on https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device
