### ISSUE TITLE
Audio but no video - Invalid data found when processing input

### ISSUE THREAD

**Issue by maxellnormalbias** [irtimmer/moonlight-embedded#485]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.5.0.69
**Moonlight Embedded version:** 2.2.2
**Moonlight Embedded running on:** _Thinkpad T420 [(inxi output)](http://ix.io/pks)_

**Output of Moonlight Embedded:**
[log](http://ix.io/pkt)
[gdb trace](http://ix.io/pkn)
[dmesg | grep moonlight](http://ix.io/pkm)

**What is the expected result?**

Some kind of window would come up showing Steam Big Picture.

**What happens instead of that?**

Audio, but no visuals.

**Comment by irtimmer** [comment]
Update to newer version of Moonlight Embedded
