### ISSUE TITLE
Impossible to pair with latest GFE Version

### ISSUE THREAD

**Issue by MopheusDG** [irtimmer/moonlight-embedded#491]
I no longer can pair with server since latest GFE version.

GFE 3.5.0
Moonlight latest version available running through Libreelec 8.0.1 on rpi3.

Used to works fine till last update of GFE.

**Comment by irtimmer** [comment]
Pairing between Moonlight Embedded 2.3.0 and latest Geforce Experience 3.5.0.70 works fine
