### ISSUE TITLE
Add support for 1440p, 2K, 4K resolutions

### ISSUE THREAD

**Issue by bonkersGER** [irtimmer/moonlight-embedded#498]
Hello 

ist it possible to add support for 1440p, 2K, 4K resolutions

https://github.com/moonlight-stream/moonlight-android/pull/123/commits/1378ce024e60f5567df67b7f22fe369f91875164

Got an ASUS Tinkerboard with "Rasbian" works fine with 1080p60fps but it should be capable of more

**Comment by irtimmer** [comment]
The Tinkerboard isn't supported so you are propably using the software decoder. I doubt if it is capable of doing 4K decoding in software.
