### ISSUE TITLE
Stuttering....Router problem? I have better performance in wifi than ethernet

### ISSUE THREAD

**Issue by Dustman71** [irtimmer/moonlight-embedded#499]
NVidia Geforce Experience version: 382.05
Moonlight Embedded verion: 2.3.0
Moonlight Embedded running on: Raspberry Pi 3

I do not understand, but I have better performance in wifi than ethernet.
I have tried with my mobile connected in the Wifi (5G) and the result is very smooth but in my Raspberry 3 connected by ethernet I have lag - stuttering.

I have tried different resolutions and fps with the same result.

I assume the problem may be in my Router ???

I hope someone can help me ... I'm desperate ..

regards

**Comment by 7hunderbug** [comment]
Try turning off IPV6 on your RaspberryPi, you router and your Windows box.

Try forcing your ethernet ports on your router and Windows box to 
100Mbps rather than 1000Mbps / 1Gbps

**Comment by Dustman71** [comment]
Too many things that I don't know how to do.
Anyway .. I can't be changing the parameters every time I stream in the Pi
I have only tried to forcing my Windows box to 100Mbps full duplex without results

thank you anyway

**Comment by irtimmer** [comment]
If you don't want to change anything there is nothing we can do

**Comment by georgcmef** [comment]
Kinda running into the same problem. Should I disable ipv6 on the network adapter or should i change the registry key in windows? 

Thank you.
