### ISSUE TITLE
Stutter sound and picture

### ISSUE THREAD

**Issue by Galcian1** [irtimmer/moonlight-embedded#500]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.6.0.74
**Moonlight Embedded version:**2.3.0
**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
Raspberry Pi 3. OSMC or retropie. 
**Output of Moonlight Embedded:** I don't know much about linux or how you log moonlight. I do now i get an OOS audio date error. And its always 1 frame off. I also get a Loss stats: Transaction failed: 11  That's the only 2 error i can see when i start and shutdown moonlight after a long play session.
**What is the expected result?** Smooth streaming
**What happens instead of that?** It streams, but sound and picture sometimes stutter.  It is fine for say a minute or 2 . Then it begins, sound stutters and i get lag.  Then its fine for a minute and it starts again. 

I tried to reinstall drivers on windows . Switched from retropie to osmc with luna. Still the same problem. Tried to connect my pc and pi to my router without a switch. Tried the 100mbit setting on my pc.

Don't really know what the error's mean so. I think the loss stats has something to do with moonlight and GFE not working together properly ( think i read it here somewere) The OOS audio i have no idea. 

Hope someone can help me look in the right direction. I'm new with linux so troubleshooting is not that easy.  Btw,srry for the bad English. Its nor my mother language.

**Comment by irtimmer** [comment]
Please update to the new version to check if it solves your issue.
