### ISSUE TITLE
Got an additional PC monitor, now moonlight showing whitescreen when starting a game

### ISSUE THREAD

**Issue by sirus887** [irtimmer/moonlight-embedded#503]
Please provide the following info.

**_NVidia Geforce Experience version: 3.6.0.74
**Moonlight Embedded version: 2.3.0
**Moonlight Embedded running on: Raspberry Pi

**Output of Moonlight Embedded:
Hi, I just bought an additional monitor for my PC and noticed that my stream is now not working correctly.
I load up moonlight with " moonlight stream  ""ip address" -1080 -60fps -mapping /opt/retropie/configs/moonlight/xbox.map". Steam comes up fine but when I start up Rage, I get a white screen but can hear the sounds of the game.

Things I've done:
1. Disabled a monitor before running moonlight. Done this with both monitors
2. Changed Big picutre modes resoultions settings to force change monitor screen.

PC SPEC:
GTX 970, 4770k with 8GB
2 Acer monitors, One is 22 inch plugged into HDMI and the other is 23 plugged into DVI.

**What is the expected result?
Game should be visable to play as before.

**What happens instead of that?**
Whitescreen, can hear the game sounds and use the control(tested by hear scroll sounds) but just can see what I am doing. Game appears fine on PC montior

**Comment by irtimmer** [comment]
This seems to be an issue with GFE and not with Moonlight Embedded.
