### ISSUE TITLE
Raspberry Pi 3 + 1080p60 = big latency

### ISSUE THREAD

**Issue by kriegalex** [irtimmer/moonlight-embedded#505]
Running moonlight-embedded on 720p30, 720p60 and 1080p30 works very well, even with bitrate at 20000, but as soon as it gets to 1080p60, it goes from perfectly playable to unplayable due to heavy latency (not far from 1 second without measuring).

Is this sudden latency expected or a bug ? I am running moonlight-embedded 2.3.0 on Raspberry Pi 3 with ethernet cable connected directly to PC through one single Netgear switch. Geforce Experience is Win10 x64 3.6.0.74.

What I find strange is the big jump of latency going from 1080p30 to 1080p60. Is this the limit of the Raspberry Pi 3 CPU hitting hard ? Are there other alternatives to handle 1080p60 other than nvidia shield if this is not a bug?

**Comment by kriegalex** [comment]
I just looked at the new issue template and don't see what's missing...

**Comment by irtimmer** [comment]
The issue template isn't new... and you're missing the output of Moonlight Embedded.
