### ISSUE TITLE
Moonlight map tries connecting to server

### ISSUE THREAD

**Issue by sville2000** [irtimmer/moonlight-embedded#511]
I used this guide to set up Moonlight: https://youtu.be/pYoLOoBkEnU

Most recent version of GeForce Experience as of writing
Moonlight 2.4.0
I got Moonlight from the repository
Raspberry Pi 3
RetroPie

I'm trying to map my DualShock 3 controller to Moonlight using
'''
moonlight map PS3.map
"'
which responds with
'''
Connecting to PS3.map...
Can't connect to server PS3.map
'''
When I start up Moonlight, it says that there is no mapping available and it starts Big Picture, but I can't move anywhere. Any advice is helpful, thank you

**Comment by gabrielpiccolo4** [comment]
Same here, maybe it's related with this issue: https://github.com/irtimmer/moonlight-embedded/issues/510

```
pi@pipplware:~/RetroPie/roms/moonlight $ moonlight map controller.map
Connect to controller.map...
Can't connect to server controller.map
```

**Comment by irtimmer** [comment]
Map commando doesn't exist

**Comment by gabrielpiccolo4** [comment]
Hey @irtimmer has this command changed? How do we map the controller.map now? Thanks!

**Comment by jbenleo** [comment]
Hi @gabrielpiccolo4, I found there is a configuration file /usr/share/moonlight/gamecontrollerdb.txt with all devices ids and configurations. Maybe your controller isn't there. 
I have added mine by copying a similar one (Generic X-Box) at the end of the file and changing the id. You may read the id at file /proc/bus/input/devices ('I' field) and adding four zeros at the end of each parameter.
{Bus}0000{Vendor}0000{Product}0000{Version}0000.
I hope this help you to get your controller working again.
