### ISSUE TITLE
egl.c compile error

### ISSUE THREAD

**Issue by bkacjios** [irtimmer/moonlight-embedded#523]
**_NVidia Geforce Experience version:_** N/A
**Moonlight Embedded version:** 2.4.2
**Moonlight Embedded source:** release 2.4.2
**Moonlight Embedded running on:** Raspberry Pi 2
**Moonlight Embedded running on distribution:** Arch Linux

**Verbose output `-verbose` of Moonlight Embedded:** N/A

Basically, line 176 in src/video/egl.c is trying to use "True" instead of "true"

```
[ 50%] Building C object CMakeFiles/moonlight.dir/src/video/egl.c.o
/tmp/moonlight-embedded-2.4.2/src/video/egl.c: In function ‘egl_draw’:
/tmp/moonlight-embedded-2.4.2/src/video/egl.c:176:15: error: ‘True’ undeclared (first use in this function); did you mean ‘true’?
     current = True;
               ^~~~
               true
/tmp/moonlight-embedded-2.4.2/src/video/egl.c:176:15: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/moonlight.dir/build.make:423: CMakeFiles/moonlight.dir/src/video/egl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/moonlight.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Fixing this allows it to compile successfully.

**Comment by irtimmer** [comment]
Fixed with commit 9cd09b36e066af8a2e605812372824c4f29f00d1
