### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by pabermod** [irtimmer/moonlight-embedded#525]
https://github.com/irtimmer/moonlight-embedded/blob/dc8211514e05f5b1c65629a9e1e22f45d5235987/CMakeLists.txt

Shows incorrect version

**Comment by qyark** [comment]
Having the same issue

**Comment by irtimmer** [comment]
Fixed with commit b6b47d30048c36ab0ca9b50359692fe2511fa32a
