### ISSUE TITLE
X-Box 360 Wired & Logitech Incorrect Mapping?

### ISSUE THREAD

**Issue by JoePata** [irtimmer/moonlight-embedded#528]
**NVidia Geforce Experience version:** 3.7.0.81
**Moonlight Embedded version:** 2.4.1
**Moonlight Embedded source:** repository
**Moonlight Embedded running on:** Raspberry Pi
**Moonlight Embedded running on distribution:** RetroPie

---

### **Issue**

Did not seem to find anyone with same issue online. Restarted from clean slate - reformatted SD, reinstalled RetroPie, reinstalled Moonlight, deleted Steam appData and reinstalled Steam. Wasn't sure if something was overriding controller configurations in mapping. Hopefully below helps you guys out or at least another person that was in same situation as me.

#### Microsoft X-Box 360 pad (030000005e0400008e02000014010000)
- Incorrect mapping - Wrong buttons mapped (E.g Right trigger mapped to start button, Left trigger mapped to back/select button, etc.), and some missing bindings

#### Logitech Gamepad F310 (030000006d0400001dc2000014400000)
- Incorrect mapping - Wrong buttons mapped (E.g Right trigger mapped to start button, Left trigger mapped to back/select button, etc.), and some missing bindings
- Trigger sensitivity non-existent for correct mapping. Acts as if I'm holding button down.

#### Logitech Logitech Rumblepad 2 USB (030000006d04000018c2000011010000)
- Mapping does not exist
- Trigger sensitivity non-existent for correct mapping. Acts as if I'm holding button down.

---

#### Microsoft X-Box 360 pad
`Detected Microsoft X-Box 360 pad (030000005e0400008e02000014010000) on /dev/input/event2 as X360 Controller`

#### Logitech Gamepad F310
`Detected Logitech Gamepad F310 (030000006d0400001dc2000014400000) on /dev/input/event0 as Logitech F310 Gamepad (XInput)`

#### Logitech Logitech Rumblepad 2 USB
`No mapping available for Logitech Logitech Rumblepad 2 USB (030000006d04000018c2000011010000) on /dev/input/event0`

---

##### Incorrect
`030000005e0400008e02000014010000,X360 Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux,`
##### Correct
`030000005e0400008e02000014010000,X360 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b2,y:b3,platform:Linux,`

##### Incorrect
`030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,`
##### Correct
`030000006d0400001dc2000014400000,Logitech F310 Gamepad (XInput),a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b2,y:b3,`

##### Below entry contains correct mapping but does not have correct ID for controller identified (030000006d04000018c2000011010000) - 11010000 vs 10010000
`030000006d04000019c2000010010000,Logitech Cordless RumblePad 2,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b0,y:b3,`

---

### **What happens instead of that?**
Mapping for above controllers were incorrect on my system.

---

PS - Thanks guys for all you do! :)

**Comment by irtimmer** [comment]
It's easy to explain why you don't have any trigger sensitivity as in your "correct" mappings the triggers are mapped as buttons. For some reason RetroPie provides its own xpad driver which is patched to map triggers to buttons ( https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/xpad.sh ). Therefore it makes almost all our mappings incorrect on their distribution. Probably the same problem exists if you use any other SDL2 based application on RetroPie. Although they may have fixed that by providing their own patched SDL2.

As RetroPi doesn't use the default settings for the driver we don't support it.
