### ISSUE TITLE
Xbox 360 wireless gamepad is detected twice

### ISSUE THREAD

**Issue by Lesoyu** [irtimmer/moonlight-embedded#530]
**_NVidia Geforce Experience version:_** 3.7.0.81
**Moonlight Embedded version:** 2.4.2 reported as 2.4.1
**Moonlight Embedded source:** repository
**Moonlight Embedded running on:** Raspberry Pi 3
**Moonlight Embedded running on distribution:** Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**
```
Moonlight Embedded 2.4.1 (EMBEDDED;ALSA;PI)
Connect to x.x.x.x...
NVIDIA GeForce GTX 980 Ti, GFE 3.7.0.81 (gs_03_80_22266601, 7.1.380.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Detected Xbox 360 Wireless Receiver (XBOX) (030000005e040000a102000007010000) on /dev/input/event0 as Xbox 360 Wireless Receiver (XBOX)
No mapping available for Xbox 360 Wireless Receiver (XBOX) (030000005e040000a102000007010000) on /dev/input/event0
Stream 1920 x 1080, 60 fps, 30000 kbps
Initializing platform...done
```
**gamecontrollerdb.txt entry:**
```
030000005e040000a102000007010000,Xbox 360 Wireless Receiver (XBOX),a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.0,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,platform:Linux,
```
**Issue**
After a change to SDL in 2.4.0, I added the correct mapping - everything worked flawlessly.
In 2.4.1, the gamepad's DPAD would only work after I restarted the stream couple times and after the latest update the gamepad doesn't work at all.

It's only one wireless receiver and one gamepad. Doesn't matter what I do it always seems to detect a non working duplicate.

**Comment by irtimmer** [comment]
Already fixed in 76cf6f633949c35a6e4d99c201b45f990c411400
