### ISSUE TITLE
quit option doesn't work

### ISSUE THREAD

**Issue by posti85** [irtimmer/moonlight-embedded#534]
**NVidia Geforce Experience version:** 3.7.0.81
**Moonlight Embedded version:** 2.4.2-1jessie1
**Moonlight Embedded source:** repository
**Moonlight Embedded running on:** Raspberry Pi
**Moonlight Embedded running on distribution:** OSMC

When I execute `moonlight quit` (to free resources after moonlight has been used and killed with Ctrl+C), it starts moonlight again instead of quiting it.

**Comment by geekycow** [comment]
Forgive me for suggesting something so basic, and I don't know how things work on OSMC, but is it possible that the original moonlight task is running as a different user than the one that's issuing the `moonlight quit` command?  Have you tried sudo moonlight quit or sudo -u <user that initiated a the track> moonlight quit`?  (Sorry if I'm being patronising.)

**Comment by irtimmer** [comment]
The quit command will quit the game on the host and not Moonlight itself. Therefore it starts Moonlight to find and connect to the host to be able to quit the game.
