### ISSUE TITLE
PS3 Controller mapping emulators

### ISSUE THREAD

**Issue by DonkeyToads** [irtimmer/moonlight-embedded#538]
Please provide the following info.

**_NVidia Geforce Experience version: GTX970**
**Moonlight Embedded version:*2.4.1*
**Moonlight Embedded source:**     http://archive.itimmer.nl/raspbian/moonlight wheezy main
**Moonlight Embedded running on:** Raspberry Pi 3
**Moonlight Embedded running on distribution:** Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**
Try to bind the keys in emulators, FCEUX, Nestopia, Snes9x, Project64 & Mupen64

**What happens instead of that?**
The controller works flawlessly in Steam, Skyrim and I can set the keys in Nestopia. I use keyboad witch mousepad (Logitech K400r) and all the emulators respond to that aswell.  But in the other emulators there is no imput from the PS3 controller. I have tried every setup i can think of but I cannot make it work.
Any Ideas?

**Comment by irtimmer** [comment]
This is a well known issue for Geforce Experience and therefore can't be fixed in Moonlight

https://forums.geforce.com/default/topic/596931/shield-portable/steam-project-64-shield-controls-don-t-work/
https://forum.xda-developers.com/showthread.php?t=2431192
