### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by DocMAX** [irtimmer/moonlight-embedded#542]
I noticed that my keyboard layout is not correct when streaming. (english, not german (z/y is switched). How can i fix this?

NVidia Geforce Experience version: 3.8.0.89
Moonlight Embedded version: 2.4.2
Moonlight Embedded source: arch AUR
Moonlight Embedded running on: X11/VAAPI
Moonlight Embedded running on distribution: Arch Linux_

**Comment by irtimmer** [comment]
Moonlight is currently QWERY only, see also #55
