### ISSUE TITLE
Xbox Wireless Receiver is not mapped

### ISSUE THREAD

**Issue by TheSpartan94** [irtimmer/moonlight-embedded#543]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.8.0.89
**Moonlight Embedded version:** 2,4,1
**Moonlight Embedded source:** raspbian/jessie
**Moonlight Embedded running on:** Raspberry Pi 3
**Moonlight Embedded running on distribution:** Retropie rom

**Verbose output `-verbose` of Moonlight Embedded:**
$ moonlight stream -verbose -fps 60 -1080 192.168.1.6
Moonlight Embedded 2.4.1 (EMBEDDED;ALSA;PULSE;PI)
Connect to 192.168.1.6...
NVIDIA GeForce GTX 970, GFE 3.8.0.89 (gs_04_00_22507081, 7.1.400.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
Detected Xbox 360 Wireless Receiver (030000005e040000a102000000010000) on /dev/input/event0 as X360 Wireless Controller
No mapping available for Xbox 360 Wireless Receiver (030000005e040000a102000000010000) on /dev/input/event0
Stream 1920 x 1080, 60 fps, 20000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Error: cannot keep up

**What is the expected result?**
The controller should be correctly mapped automatically by moonlight and working on the Steam Big Picture interface.

**What happens instead of that?**
No binding for the controller, no input button works. No action is possible. No custom mapping via the "-map" argument nor modification of any gamecontrollerdb.txt file works.

**Comment by irtimmer** [comment]
You are using an old version of Moonlight and this bug has already been reported (#514)
