### ISSUE TITLE
Support for Tinker Board?

### ISSUE THREAD

**Issue by r3claim** [irtimmer/moonlight-embedded#544]
Dear irtimmer,

I just wanted to ask, if there is any possibility to run moonlight-embedded on a Tinker Board?

Greetings,
reclaim

**Comment by irtimmer** [comment]
You can compile Moonlight with software decoder support (ffmpeg) but the Rockchip in the Tinker Board is currently not supported.

**Comment by adamkex** [comment]
Are there any plans for supporting the Rockchip?
