### ISSUE TITLE
Libenet7 

### ISSUE THREAD

**Issue by Furno221** [irtimmer/moonlight-embedded#546]
Please provide the following info.

**_NVidia Geforce Experience version:_** 3.8.0.89
**Moonlight Embedded version:** newest i guess 2.4.2
**Moonlight Embedded source:** archive.itimmer.nl/raspbian/moonlight jessie main
**Moonlight Embedded running on:** Raspberry Pi 3
**Moonlight Embedded running on distribution:** Raspbian Jessie

**Verbose output `-verbose` of Moonlight Embedded:**
The following packages have unmet dependencies:
 moonlight-embedded : Depends: libenet7 but it is not installable
E: Unable to correct problems, you have held broken packages.
Please provide the following info.

**What is the expected result?**
I tried to install moonlight-embedded with sudo apt-get install moonlight-embedded
**What happens instead of that?**
This error 

Sorry for my bad English.

**Comment by irtimmer** [comment]
Libenet7 is a package available is the Debian repository, so this is clearly a system issue and not a Moonlight bug.
