### ISSUE TITLE
Failed to sign data

### ISSUE THREAD

**Issue by bodanu** [irtimmer/moonlight-embedded#547]
Hello i have:
NVidia Geforce Experience version:_3.9.0.61
Moonlight Embedded version:2.4.3
From http://archive.itimmer.nl/raspbian/moonlight jessie main
Moonlight Embedded running on:** _Raspberry Pi 3
**Moonlight Embedded running on raspbian

Whenever i try to pair with my computer i get the following:
Failed to conect to server. Failed to sign data
What am I doing wrong?

**Comment by irtimmer** [comment]
That isn't supposed to happen. Try to clean $XDG_CACHE_DIR/moonlight or ~/.cache/moonlight , maybe the keys got corrupted.

**Comment by badmikey83** [comment]
how can i do this?

**Comment by Unorthodactyl** [comment]
Are you using raspbian stretch? Try running it with sudo

**Comment by badmikey83** [comment]
yes i do. what´s the command? sorry i´m new

**Comment by bodanu** [comment]
Can someone help me how should i do this? Iam really a noob with CLI.
Thank you.

**Comment by bodanu** [comment]
Never mind i did it :) now it works fine thank you so much !
