### ISSUE TITLE
L/R triggers not recognized on Logitech Cordless RumblePad 2

### ISSUE THREAD

**Issue by Meems33** [irtimmer/moonlight-embedded#550]
I'm using the Logitech Cordless RumblePad 2 with moonlight streaming. It seems that the L/R triggers (buttons labeled 7/8 mapped to b6/b7) are not recognized on their own. If I press them along with pressing another button the hit registers. If I hold one down and let go of another button that was pressed the game will continue to register the trigger as on. Evidently (see update 2) there are no data packets being sent if just the L/R triggers change state - it seems to require another button to change for the packet to get sent.

I have used jstest and evtest to verify that the mapping in [gamecontrollerdb.txt](https://github.com/irtimmer/moonlight-embedded/blob/master/gamecontrollerdb.txt) is correct. 

Here are 3 samples in Steam. All exhibit the same behavior (button hit alone not recognized, button hit with other buttons recognized):
- Portal 2
- Rocket League
- Lego Marvel Superheros

**Update**
The trigger buttons b6 and b7 almost work on this webpage with the webpage on the host pc and the controller on the streaming pi - http://html5gamepad.com/. It shows up as gamepad 2 "Xbox 360 Controller (XInput STANDARD GAMEPAD)". The trigger buttons only register if I press another button with it. If I press a trigger button all by itself it does not register the button push.

The trigger buttons b6 and b7 DO work on the same webpage if run from a browser on the pi with the controller on the pi. It shows up as gamepad 1 "Logitech Logitech Cordless RumplePad 2 (Vendor: 046d Product: c219)".

How do I get the vendor and product to be recognized on the host pc while streaming it from the pi?

**Update 2**
Using wireshark I can tell when a packet is received that has some kind of input change. When idle the UDP packets are of size 60 and 86. When input data comes in the size is 108 (aka a button is pressed or a stick is moved). There are no 108 byte packages received when I push the L/R triggers by themselves. Hence the issue is that pressing the trigger does not seem to be triggering something to send out a new data packets.

**_NVidia Geforce Experience version:_**
3.9.0.61
**Moonlight Embedded version:**
2.4.2ish

**Moonlight Embedded source:** _repository/included in distribution/compiled from source/..._
compiled against commit [3568934860bf5b3989e0e9cc79d1e577d51ac56c](https://github.com/irtimmer/moonlight-embedded/commit/3568934860bf5b3989e0e9cc79d1e577d51ac56c)

**Moonlight Embedded running on:** _Raspberry Pi/Cubox-i/Hummingboard/Other linux device/..._
Pi 3b
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._
Raspbian

(it appears I am using evdev for the joystick so this may not be relevant)
> $ sudo apt list --installed / grep xpad
> xpad/oldstable,now 4.1-1 armhf [installed]

>  $ lsmod
> Module                  Size  Used by
> bnep                   12051  2
> hci_uart               20020  1
> btbcm                   7916  1 hci_uart
> bluetooth             365511  22 hci_uart,bnep,btbcm
> brcmfmac              222874  0
> evdev                  12423  9
> joydev                  9988  1
> brcmutil                9092  1 brcmfmac
> hid_logitech           25945  0
> cfg80211              543027  1 brcmfmac
> ff_memless              5315  1 hid_logitech
> rfkill                 20851  4 bluetooth,cfg80211
> snd_bcm2835            24427  1
> snd_pcm                98501  1 snd_bcm2835
> snd_timer              23968  1 snd_pcm
> snd                    70032  5 snd_timer,snd_bcm2835,snd_pcm
> bcm2835_gpiomem         3940  0
> uio_pdrv_genirq         3923  0
> fixed                   3285  0
> uio                    10204  1 uio_pdrv_genirq
> i2c_dev                 6913  0
> fuse                   99603  3
> ipv6                  408971  64

> $ evtest
> Input driver version is 1.0.1
> Input device ID: bus 0x3 vendor 0x46d product 0xc219 version 0x110
> Input device name: "Logitech Logitech Cordless RumblePad 2"
> Supported events:
>   Event type 0 (EV_SYN)
>   Event type 1 (EV_KEY)
>     Event code 304 (BTN_SOUTH)
>     Event code 305 (BTN_EAST)
>     Event code 306 (BTN_C)
>     Event code 307 (BTN_NORTH)
>     Event code 308 (BTN_WEST)
>     Event code 309 (BTN_Z)
>     Event code 310 (BTN_TL)
>     Event code 311 (BTN_TR)
>     Event code 312 (BTN_TL2)
>     Event code 313 (BTN_TR2)
>     Event code 314 (BTN_SELECT)
>     Event code 315 (BTN_START)
>   Event type 3 (EV_ABS)
>     Event code 0 (ABS_X)
>       Value    128
>       Min        0
>       Max      255
>       Flat      15
>     Event code 1 (ABS_Y)
>       Value    127
>       Min        0
>       Max      255
>       Flat      15
>     Event code 2 (ABS_Z)
>       Value    127
>       Min        0
>       Max      255
>       Flat      15
>     Event code 5 (ABS_RZ)
>       Value    128
>       Min        0
>       Max      255
>       Flat      15
>     Event code 16 (ABS_HAT0X)
>       Value      0
>       Min       -1
>       Max        1
>     Event code 17 (ABS_HAT0Y)
>       Value      0
>       Min       -1
>       Max        1
>   Event type 4 (EV_MSC)
>     Event code 4 (MSC_SCAN)
>   Event type 21 (EV_FF)
>     Event code 80 (FF_RUMBLE)
>     Event code 81 (FF_PERIODIC)
>     Event code 88 (FF_SQUARE)
>     Event code 89 (FF_TRIANGLE)
>     Event code 90 (FF_SINE)
>     Event code 96 (FF_GAIN)
> Properties:
> Testing ... (interrupt to exit)

**Button map from evtest**
Button 1 (left): 304 (BTN_SOUTH)
Button 2 (buttom): 305 (BTN_EAST)
Button 3 (right): 306 (BTN_C)
Button 4 (top): 307 (BTN_NORTH)
Button 5 (left bumper): 308 (BTN_WEST)
Button 6 (right bumper): 309 (BTN_Z)
Button 7 (left trigger): 310 (BTN_TL)
Button 8 (right trigger): 311 (BTN_TR)
Button 9 (select): 312 (BTN_TL2)
Button 10 (start): 313 (BTN_TR2)
Macro Button (?): 1 (ABS_Y)
Vibrate Button: N/A
DPAD left (dpad is on the top left instead of bottom left): 16 (ABS_HAT0X) -1
DPAD right (dpad is on the top left instead of bottom left): 16 (ABS_HAT0X) 1
DPAD up (dpad is on the top left instead of bottom left): 17 (ABS_HAT0Y) -1
DPAD down (dpad is on the top left instead of bottom left): 17 (ABS_HAT0Y) 1
Left stick left: 0 (ABS_X) 0-127
Left stick right: 0 (ABS_X) 129-255
Left stick up: 1 (ABS_Y) 0-126
Left stick down: 1 (ABS_Y) 128-255
Left stick pushed in: 314 (BTN_SELECT) 1
Right stick left: 2 (ABS_Z) 0-126
Right stick right: 2 (ABS_Z) 128-255
Right stick up: 5 (ABS_RZ) 0-127
Right stick down: 5 (ABS_RZ) 129-255
Right stick pushed in: 315 (BTN_START) 1

**Verbose output `-verbose` of Moonlight Embedded:**

>  moonlight -verbose stream
> Moonlight Embedded 2.4.1 (EMBEDDED;ALSA;PULSE;PI)
> Searching for server...
> Connect to 192.168.0.115...
> NVIDIA GeForce GTX 1060 6GB, GFE 3.9.0.61 (gs_04_00_22663502, 7.1.400.0)
> Platform Raspberry Pi (Broadcom)
> Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
> No mapping available for   USB Keyboard (03000000d90400000316000010010000) on /dev/input/event1
> Detected Logitech Logitech Cordless RumblePad 2 (030000006d04000019c2000010010000) on /dev/input/event4 as Logitech Cordless RumblePad 2
> Stream 1280 x 720, 60 fps, 10000 kbps
> Initializing platform...done
> Resolving host name...done
> Starting RTSP handshake...done
> Initializing control stream...done
> Initializing video stream...done
> Initializing audio stream...done
> Initializing input stream...done
> Starting control stream...done
> Starting video stream...done
> Starting audio stream...done
> Starting input stream...done
> Returning RTP packet queued for too long
> Received OOS audio data (expected 12023, but got 12024)

**What is the expected result?**
Games recognize the L/R triggers

**What happens instead of that?**
Some games are not recognizing the L/R triggers

**Comment by Meems33** [comment]
I believe it would work if I could get the host pc to recognize the controller as "Logitech Logitech Cordless RumplePad 2 (Vendor: 046d Product: c219)" instead of "Xbox 360 Controller (XInput STANDARD GAMEPAD)". The latter causes the trigger buttons to register only if I press another button with it. If I press a trigger button all by itself it does not register the button push.

**Comment by Meems33** [comment]
Using wireshark I can tell when a packet is received that has some kind of input change. When idle the UDP packets are of size 60 and 86. When input data comes in the size is 108 (aka a button is pressed or a stick is moved). There are no 108 byte packages received when I push the L/R triggers by themselves. Hence the issue is that pressing the trigger does not seem to be triggering something to send out a new data packets.

**Comment by Meems33** [comment]
I believe I have found the problem. Looking at the code in evdev.c the trigger cases do not appear to set the gamepadModified flag to true. PR @ #552

**Comment by irtimmer** [comment]
Bug have been fixed with commit a4e19af04f56a266b7d8bd657e3c3ba3210b21cc
