### ISSUE TITLE
build error with libcec

### ISSUE THREAD

**Issue by MrCapone** [irtimmer/moonlight-embedded#557]
**Moonlight Embedded version:** git 06c3c7a
**Moonlight Embedded source:** compiled from git repository
**Moonlight Embedded running on:** UDOO Quad based on imx6
**Moonlight Embedded running on distribution:** Udoobuntu based on Ubuntu 14.04
**CMake version** 3.2.2
**gcc version** `gcc (Ubuntu/Linaro 5.4.1-2ubuntu1~14.04)` 
**g++ version** `g++ (Ubuntu/Linaro 5.4.1-2ubuntu1~14.04)`

**What is the expected result?**
I installed _libcec-dev(3.0.1+dfsg2-9build1)_ and _libcec-platform-dev(3.0.1+dfsg2-9build1)_ and execute `cmake`. CMake found module libcec v3.0.1. Then i execute make.

**What happens instead of that?**
build error
```
[ 65%] Building C object CMakeFiles/moonlight.dir/src/input/cec.c.o
/home/udooer/moonlight-embedded/src/input/cec.c: In function ‘cec_init’:
/home/udooer/moonlight-embedded/src/input/cec.c:78:14: error: ‘ICECCallbacks {aka struct ICECCallbacks}’ has no member named ‘keyPress’
   g_callbacks.keyPress = &on_cec_keypress;
              ^
make[2]: *** [CMakeFiles/moonlight.dir/src/input/cec.c.o] Error 1
make[1]: *** [CMakeFiles/moonlight.dir/all] Error 2
make: *** [all] Error 2
```

**Possible solution**

on `/usr/include/libcec/cectypes.h` i found struct `ICECCallbacks` with member `CBCecKeyPressType CBCecKeyPress;`

**Comment by irtimmer** [comment]
Moonlight requires at least libcec 4.0 for CEC support. Since commit 0238a22 it will no longer try to include support when using an older version
