### ISSUE TITLE
Keep streaming PC locked while using moonlight?

### ISSUE THREAD

**Issue by Red881** [irtimmer/moonlight-embedded#567]
As in operating the game/desktop on the device running moonlight while the PC is locked. 
Is this possible? Microsoft's remote desktop is able to achieve this. Would be nice.

**Comment by irtimmer** [comment]
No this is currently not possible. This kind of functionality has to be implemented in NVidia's Geforce Experience which isn't the case. Currently GFE captures directly from the framebuffer of the screen output and therefore the computer has to be unlocked.
