### ISSUE TITLE
Repo down? 

### ISSUE THREAD

**Issue by rodobodolfo** [irtimmer/moonlight-embedded#575]
Hi, im trying to download moonlight embedded but i get a 503 service unavailable

`root@raspberrypi:/home/pi# apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Ign:3 http://archive.itimmer.nl/raspbian/moonlight jessie InRelease
Ign:4 http://archive.itimmer.nl/raspbian/moonlight jessie Release
Ign:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Ign:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Ign:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Ign:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Ign:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Err:5 http://archive.itimmer.nl/raspbian/moonlight jessie/main armhf Packages
  503  Service Unavailable
Ign:6 http://archive.itimmer.nl/raspbian/moonlight jessie/main all Packages
Ign:7 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en
Ign:8 http://archive.itimmer.nl/raspbian/moonlight jessie/main Translation-en_GB
Reading package lists... Done
W: The repository 'http://archive.itimmer.nl/raspbian/moonlight jessie Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://archive.itimmer.nl/raspbian/moonlight/dists/jessie/main/binary-armhf/Packages  503  Service Unavailable
E: Some index files failed to download. They have been ignored, or old ones used instead.
`
and via http:

![imagen](https://user-images.githubusercontent.com/12578313/31569131-f0e80e44-b04e-11e7-902f-89a697e19ffe.png)

Thanks,
rodo

**Comment by irtimmer** [comment]
Yes, repo was down
