### ISSUE TITLE
DS4 input config strange behavior

### ISSUE THREAD

**Issue by craciant** [irtimmer/moonlight-embedded#588]
Please provide the following info.

NVidia Geforce Experience version: 3.9.0.97
Moonlight Embedded version: 2.4.1
Moonlight Embedded source: repository/included in distribution/compiled from source/...
Moonlight Embedded running on: Raspberry Pi/Cubox-i/Hummingboard/Other linux device/...
Moonlight Embedded running on distribution: Arch Linux/Raspbian/OpenELEC/...

DS4 Connected using Sony Wireless Adapter

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**
Buttons mapped correctly

**What happens instead of that?**
Using Gamecontrollersdb.txt settings, pressing Dpad UP is interpreted as Dpad Right. None of the other Dpad buttons do anything. 

I messed with the settings for a bit, when I deleted the configs for Dpad UP, Left, and Down and assigned dpad right to h0.1 which was previously assigned to UP, I instead get only a response from pressing the left button which produces a DOWN response. 

I can't begin to figure out whats wrong. I've spent a long time trying to figure this out, the output from EVtest is no help as I can't correlate that to how this configuration works. Can't find any documentation. 

030000004c050000a00b000011010000,Sony DualShock 4 Wireless Adaptor,a:b2,b:b1,y:b0,x:b3,start:b9,guide:b12,back:b8,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h1.8,dpleft:h2.2,dpdown:h1.2,dpright:h0.1,leftx:a0,lefty:a1,rightx:a2,righty:a5,lefttrigger:a3,righttrigger:a4,platform:Linux,

Also, back for the DS4 with wireless adapter is B8 not B13.

**Comment by irtimmer** [comment]
You need at least version 2.4.2 to get a working D-pad as there was a bug in version 2.4.0 and 2.4.1
