### ISSUE TITLE
Can't map controller

### ISSUE THREAD

**Issue by TheOnePhoenix** [irtimmer/moonlight-embedded#589]
I'm currently using the latest version of moonlight on my raspberry pi 3 model b. I want to map my controller with the `moonlight map controller.map` command, but it outputs this `You need to specify one input device using -input.` Anyone know why this happens and how to fix it? thank you :)

**Comment by irtimmer** [comment]
Yes, you need to specify at least one input device using the -input option.

**Comment by Blumed** [comment]
@irtimmer Do you mind elaborating? What are the commands?

**Comment by Blumed** [comment]
@TheOnePhoenix Here is a good article to take a look at if you are still stuck. 
https://www.reddit.com/r/RetroPie/comments/7bwxnf/moonlight_im_stuck/
