### ISSUE TITLE
Destiny 2 Can't Launch

### ISSUE THREAD

**Issue by Calamity1911** [irtimmer/moonlight-embedded#595]
nvidia GeForce Experience version 3.0.11.73 (finally added support for streaming Destiny 2)
Specs are: i5 4590, GTX 1060, 16gb RAM, Driver version 388.31
latest version of moonlight embedded as of 11/22/2017 (2.4.4)
Raspberry Pi 3 running Raspbian Stretch 

I installed moonlight embedded just fine and I tried to stream destiny 2, but it couldn't find the game.
I know I am supposed to have logs but I can't get them now, I'm short on time. I typed "moonlight stream [my PC's IP] -list" and Destiny 2 was option 4, so I then went and typed "moonlight stream [my PC's IP] -app Destiny 2 -1080 -fps 30 -bitrate 4000 -nosops" and it said something along the lines of could not find destiny 2. 
Again, I'll come back later with exact logs on what happened. 
I then did those same settings but with "-app Steam" and "-app mstsc.exe" and both worked just fine, so maybe it's the space in Destiny 2's name. Since the -list option displays games with numbers next to them, I then tried "-app 4" and it had the same error as Destiny 2 but the app name was "4" 

Again, I am sorry for the scant details. I will comment the exact logs in an hour or two. 

**EDIT**
That was basically instant, I found enough time to grab the logs. 
The moonlight list:
moonlight list
Searching for server...
Connect to 192.168.0.2...
1. Steam
2. mstsc.exe
3. Sid Meier's Civilization V (DX 11)
4. Destiny 2
5. Terraria
6. Team Fortress 2
7. Rocket League
8. Star Wars Battlefront
9. PlayerUnknown's Battle Grounds
10. Battlefield 1
11. Tom Clancy's The Division
12. Tom Clancy's Rainbow Six Siege
13. Minecraft: Windows 10 Edition
14. Overwatch

Moonlight stream command:
moonlight stream [computer IP] -app Destiny 2 -1080 -fps 30 -bitrate 4000 -nosops
Too many options: No such file or directory

Without IP: 
moonlight stream -app Destiny 2 -1080 -fps 30 -bitrate 4000 -nosops
Connect to 2...
Can't connect to server 2

**Comment by Calamity1911** [comment]
Alright, I feel dumb. I have the solution. 
put the game name in quotes. 
For Destiny 2:

`moonlight stream [PC IP] -1080 -fps 30 -bitrate 4000 -codec auto -nosops -app "Destiny 2"`

**Comment by Eschguy** [comment]
Good god...thank you so much. F'ing quotes...
