### ISSUE TITLE
(Cubox-i) SEVERE: Error code during decode: -5

### ISSUE THREAD

**Issue by msxmine** [irtimmer/moonlight-embedded#60]
System Spec:
Cubox-i4
Limelight:
Limelight-embedded 1.1.1
OS:Latest Openelec build with opus added from debian wheezy
(Same error on arch linux (imx-vpu installed))
Tested both with and without XBMC running in foreground
Java:
Java SE Development Kit 8 Update 6 for ARM
Linux 32-bit ARM v6/v7 Hard Float ABI
(Tried running both as user 'xbmc' and as root)
Host:
Windows 7 Geforce Experience 2.1.4.1/Nvidia driver 344.75

Pairing and starting app works, but after that, limelight starts outputting error messages to console (SSH). On host steam pops up normally.

Console output:
./jdk1.8.0_06/jre/bin/java -jar ./limelight3.jar stream -nosops -1080 192.168.1.99
Starting app
Starting RTSP handshake
Starting control connection
Starting video stream
[INFO]	bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
Starting audio stream
Starting input connection
Dec 06, 2014 9:01:59 PM com.limelight.LimeLog severe
SEVERE: Error code during decode: -5
Dec 06, 2014 9:01:59 PM com.limelight.LimeLog severe
SEVERE: Error code during decode: -1
(Error code -1 is being repeated till java is killed)

**Comment by irtimmer** [comment]
Newer kernel versions  (>3.10) are currently unsupported
