### ISSUE TITLE
libva-x11.so.1: Missing library in ArchLinuxARM for RPi

### ISSUE THREAD

**Issue by ogarcia** [irtimmer/moonlight-embedded#600]
With latest version of moonlight for Arch Linux (moonlight-embedded-2.4.4-1-armv7h.pkg.tar.xz). You have this error on launch.
```sh
$ moonlight 
moonlight: error while loading shared libraries: libva-x11.so.1: cannot open shared object file: No such file or directory
```
The libva-x11.so.1 is missing in system. The package libva only have the version 2:
```
/usr/lib/libva-x11.so
/usr/lib/libva-x11.so.2
/usr/lib/libva-x11.so.2.0.0
```
If I have a symbolic link `libva-x11.so.1 -> libva-x11.so.2.0.0` it works but I think that moonlight must call to `libva-x11.so` directly.

**Comment by irtimmer** [comment]
New release has been rebuild against the newer libva version to fix this issue
