### ISSUE TITLE
failed -1 RTSP: Failed to connect to UDP port 48010

### ISSUE THREAD

**Issue by TheWrongBishop** [irtimmer/moonlight-embedded#612]
I have tried everything for the past day and I am still not able to solve anything.

Geforce version: 3.12.0.79
Moonlight Embedded version: 2.3.0 running on a raspbian raspberry pi

Usually, the console speeds through the RTSP handshake, but now it just hangs up for a second until I get the error. 

`RTSP: Failed to connect to UDP port 48010`
`failed -1`

So far I have tried forwarding UDP port 48010, despite being wired through ethernet on both ends.  Disabling my windows firewall and antivirus, and reinstalling my drivers.  No luck so far. 

Thanks!

**Comment by irtimmer** [comment]
Duplicate of #609
