### ISSUE TITLE
Unable to install moonlight-embedded

### ISSUE THREAD

**Issue by stefanw1337** [irtimmer/moonlight-embedded#615]
After sudo apt-get update and a lot of listing of repositories I get this:
Fetched 1 813 B in 11s (162 B/s)                                                                         
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://archive.itimmer.nl/raspbian/moonlight jessie InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'http://archive.itimmer.nl/raspbian/moonlight jessie InRelease' doesn't support architecture 'amd64'

And so: 
sudo apt-get install moonlight-embedded
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package moonlight-embedded

I can't get it to even install. I tried going for the Chrome extension version, but then my Chromium says WebGL is not supported(even after I've enabled the #ignore-gpu-blacklist thing)

**Comment by irtimmer** [comment]
There are no binary packages available for Debian i386 and amd64
