### ISSUE TITLE
Keyboard shortcut to directly quit streaming from Desktop mode?

### ISSUE THREAD

**Issue by Haris1977** [irtimmer/moonlight-embedded#652]
Please provide the following info.

**_NVidia Geforce Experience version: 3.13.1.30
**Moonlight Embedded version: 2.4.6
**Moonlight Embedded source: repository
**Moonlight Embedded running on: Raspberry Pi 1
**Moonlight Embedded running on distribution: Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**

**What happens instead of that?**

I always boot directly into desktop mode (moonlight stream -app mstsc.exe 192.168.X.XXX -1080).
Is there any **keyboard shortcut to directly quit/exit** "streaming session" from within desktop? Ctrl+Alt+Shift+Q does nothing. Thanks!

**Comment by posti85** [comment]
Same problem here.

**Comment by Haris1977** [comment]
I just put my pc in hibernate mode (start menu->hibernate) thus making raspberry to quit into shell.

**Comment by kurac338** [comment]
If my instance freezes, or I need to force quit from the "server" side, I just kill the nvidia network container in the task manager. I found this to be the quickest way, but its a dirty shutdown.
