### ISSUE TITLE
[Bug] Cannot build moonlight-embedded for Rock64 on Debian (arm64)

### ISSUE THREAD

**Issue by Sk1pp3r** [irtimmer/moonlight-embedded#654]
I'd like to request a moonlight-embedded version for [Rock64](https://www.pine64.org/?page_id=7147)  on Debian (for arm64 architecture) on the release page, or maybe someone can help with compilation.

**Moonlight Embedded version:** 2.4.6
**Moonlight Embedded running on:** Rock64
**Moonlight Embedded running on distribution:** Debian Stretch. 

I've tried installing moonlight using [the method described in the Wifi](https://github.com/irtimmer/moonlight-embedded/wiki/Compilation), and I get an error that `cmake` wasn't able to find some dependencies, even though all of them are a the lates version (specifically `libopus0` in this case).
Here is the terminal output:
```
rock64@rock64:~/repos$ sudo apt-get install libopus0 libexpat1 libasound2 libudev1 libavahi-client3 libcurl3 li bevdev2 libenet7
Reading package lists... Done
Building dependency tree
Reading state information... Done
libasound2 is already the newest version (1.1.3-5).
libavahi-client3 is already the newest version (0.6.32-2).
libenet7 is already the newest version (1.3.12+ds-2).
libexpat1 is already the newest version (2.2.0-2+deb9u1).
libevdev2 is already the newest version (1.5.6+dfsg-1).
libopus0 is already the newest version (1.2~alpha2-1).
libcurl3 is already the newest version (7.52.1-5+deb9u6).
libudev1 is already the newest version (232-25+deb9u3).
The following packages were automatically installed and are no longer required:
  libdirectfb-1.2-9 libgles1-mesa libiso9660-8 libvcdinfo0 libvlccore8
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

rock64@rock64:~/repos/moonlight-embedded$ git submodule update --init
Submodule 'common' (https://github.com/irtimmer/moonlight-common-c.git) registered for path 'third_party/moonlight-common-c'
Cloning into '/home/rock64/repos/moonlight-embedded/third_party/moonlight-common-c'...
Submodule path 'third_party/moonlight-common-c': checked out '275b43687c5efea45c1f007c2c8115a8187f4614'

rock64@rock64:~/repos/moonlight-embedded$ mkdir build
rock64@rock64:~/repos/moonlight-embedded$ cd build/
rock64@rock64:~/repos/moonlight-embedded/build$ cmake ../
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ALSA (missing:  ALSA_LIBRARY ALSA_INCLUDE_DIR)
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Opus (missing: OPUS_LIBRARY OPUS_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpus.cmake:59 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/rock64/repos/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".
```

Does anyone have any suggestions?
Thank you.

**Comment by irtimmer** [comment]
As stated on https://github.com/irtimmer/moonlight-embedded/wiki/Compilation you also need for compilation and development:

- libssl-dev
- libopus-dev
- libasound2-dev
- libudev-dev
- libavahi-client-dev
- libcurl4-openssl-dev
- libevdev-dev
- libexpat1-dev
- libpulse-dev
- uuid-dev
- libenet-dev
- cmake
- gcc
- g++
- rbp-userland-dev-osmc (Raspberry Pi and OSMC)
- libraspberrypi-dev (Raspberry Pi and Raspbian)
- fakeroot (Package creation)
- debhelper (Package creation)

**Comment by Sk1pp3r** [comment]
I've installed the packages, but cmake still shows errors:

rock64@rock64:~/Software/moonlight-embedded/build# cmake ../
-- Could NOT find Broadcom (missing:  BROADCOM_INCLUDE_DIR VCOS_LIBRARY VCHIQ_LIBRARY OPENMAXIL_LIBRARY BCM_HOST_LIBRARY)
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY)
-- Could NOT find Rockchip (missing:  ROCKCHIP_INCLUDE_DIR ROCKCHIP_LIBRARY)
-- Checking for module 'sdl2>=2.0.4'
--
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
-- Checking for module 'x11'
--   No package 'x11' found
-- Checking for module 'vdpau'
--   No package 'vdpau' found
-- Checking for module 'libva'
--   No package 'libva' found
-- Checking for module 'libva-x11'
--   No package 'libva-x11' found
-- Checking for module 'libcec>=4'
--
-- Checking for module 'egl'
--   No package 'egl' found
-- Checking for module 'glesv2'
--   No package 'glesv2' found
CMake Error at CMakeLists.txt:166 (message):
  No video output available


-- Configuring incomplete, errors occurred!
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeError.log".

**Comment by Sk1pp3r** [comment]
After installing the dependencies from [compilation wiki](https://github.com/irtimmer/moonlight-embedded/wiki/Compilation), I get the following:
```
rock64@rock64:~/Software/moonlight-embedded/build# cmake ../
-- Could NOT find Broadcom (missing:  BROADCOM_INCLUDE_DIR VCOS_LIBRARY VCHIQ_LIBRARY OPENMAXIL_LIBRARY BCM_HOST_LIBRARY)
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY)
-- Could NOT find Rockchip (missing:  ROCKCHIP_INCLUDE_DIR ROCKCHIP_LIBRARY)
-- Checking for module 'sdl2>=2.0.4'
--
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
-- Checking for module 'x11'
--   No package 'x11' found
-- Checking for module 'vdpau'
--   No package 'vdpau' found
-- Checking for module 'libva'
--   No package 'libva' found
-- Checking for module 'libva-x11'
--   No package 'libva-x11' found
-- Checking for module 'libcec>=4'
--
-- Checking for module 'egl'
--   No package 'egl' found
-- Checking for module 'glesv2'
--   No package 'glesv2' found
CMake Error at CMakeLists.txt:166 (message):
  No video output available


-- Configuring incomplete, errors occurred!
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeOutput.log".
See also "/root/Software/moonlight-embedded/build/CMakeFiles/CMakeError.log".
```

**Comment by irtimmer** [comment]
_libraspberrypi-dev_ still does seem to be missing, otherwise provide the list of installed files for this package using `dpkg-query -L libraspberrypi-dev`

**Comment by Sk1pp3r** [comment]
@irtimmer actually, rbp-userland-osmc and libraspberrypi0 (and their `dev` versions) were not found during `apt-get install`.
it would probably be best to find some kind of alternatives to these packages

**Comment by Sk1pp3r** [comment]
@irtimmer any updates on this issue?
I found `libavcodec` as part of  `ffmpeg` library, which i installed, but I still get this part when trying to build:
```
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
```

**Comment by DDMP6** [comment]
this is frustrating to see, I am sure the devs would save themselves a lot of bug reports, if there would be single HOW TO INSTALL properly documented.

**Comment by maretodoric** [comment]
Ok, i have to chime in. After thoroughly looking into CMakeLists to see what it's actually looking for and searching through raspbian repositories, I've found that taking following steps works (At least I've managed to compile and install using this method)

Some "missing files" will appear during cmake but it seems that they can be safely ignored since those files are used on some other devices rather than raspberry pi (at least i think).

Ome more thing, this is tested on Raspbarry Pi 3B+, with Raspbian 9 (Stretch)

```
sudo apt install libopus-dev libasound2-dev libudev-dev libavahi-client-dev libcurl4-openssl-dev libevdev-dev libexpat1-dev libpulse-dev uuid-dev libenet-dev gcc g++ libraspberrypi-dev fakeroot debhelper libx11-dev libvdpau-dev libva-dev libgegl-dev cmake make -y
git clone https://github.com/irtimmer/moonlight-embedded.git
cd moonlight-embedded
git submodule update --init --recursive
mkdir build
cd build
cmake ../
make
sudo make install
sudo ln -s /usr/local/bin/moonlight /usr/bin/moonlight
sudo ldconfig
```

I had to add symlink because for some reason, it was looking for moonligth in /usr/bin, even though PATH is sed for /usr/local/bin as well !
Hope it helps.
