### ISSUE TITLE
E: Unable to locate package moonlight-embedded

### ISSUE THREAD

**Issue by noobyboob** [irtimmer/moonlight-embedded#657]
Please provide the following info.

NVidia Geforce Experience version 3.13.1.30
N/A or latest Moonlight version
**Moonlight Embedded source deb http://archive.itimmer.nl/raspbian/moonlight jessie main
Running on Raspberry Pi 3 model B
Running on Raspian jessie v 8

Tried installing Moonlight:

`sudo apt-get upgrade`
*upgrade completes*
`sudo apt-get update`
*blah, blah...
E: Some index files failed to download, they have been ignored, or old ones used instead*

"Oh well," says I and:

`sudo nano /etc/apt/sources.list`
*adds source*
`sudo apt-get install moonlight-embedded`
*Reading package lists*
*Building dependency tree*
*Reading state information*
*E: Unable to locate package moonlight-embedded*

Phooey... time for some Googling... apt-clean, huh?

`sudo apt clean`

Upgrades and updates again, same result. Then:

`sudo apt upgrade`
`sudo apt update`
*You know the rest*

Attempts manual apt cleaning:

` cd /var/cache/apt/archives/`
`dpkg -l | grep ^..r `
*no broken packages*

Pulls hair out. Reboots. No change. More Googling:

`wget http://archive.itimmer.nl/itimmer.gpg`
*completes*
`sudo apt-key add itimmer.gpg`
*OK*
`sudo apt-get install moonlight-embedded`
*E: Unable to locate package moonlight-embedded*

Takes ibuprofen. Heads to bed.

**Comment by svandemore** [comment]
You probably were to get it working but I think you might have just missed refreshing the rep after adding the key.

After adding the key you have to refresh the rep.
`sudo apt-key add itimmer.gpg`
run
`sudo apt-get update`
