### ISSUE TITLE
Repo down?

### ISSUE THREAD

**Issue by ryluth** [irtimmer/moonlight-embedded#659]
Hi, 

just checking in, wondering if i'm the only one with getting 101's from http://archive.itimmer.nl/

Greets

Edit: 101's, not 404's 
    Thanks to TyanColte

**Comment by TyanColte** [comment]
Same trouble here. Ran sudo apt-get update and got the error message: cannot initiate connection to archive.itimmer.nl:80 (101: network is unreachable)
