### ISSUE TITLE
[Feature] Nintendo-Switch Port?

### ISSUE THREAD

**Issue by sh3rlock97** [irtimmer/moonlight-embedded#661]
Are there any chances that we'll get a Nintendo Switch Port? Would be awesome!

**Comment by nadaso8** [comment]
this would probably be better on the main moonlight page "I'm not sure but i think that the chrome version has ended up being the main branch at this point"

**Comment by irtimmer** [comment]
Please see https://github.com/kbhomes/moonlight-switch
