### ISSUE TITLE
Handle "DEvice Orange Controller"

### ISSUE THREAD

**Issue by MrPropre6Mt** [irtimmer/moonlight-embedded#667]
**_NVidia Geforce Experience version:_** 3.14.0.139
**Moonlight Embedded version:** 2.4.6
**Moonlight Embedded source:** repository
**Moonlight Embedded running on:** Raspberry Pi 3
**Moonlight Embedded running on distribution:** Raspbian

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**
Handle specific controller, named "DEvice Orange Controller" (ref: https://boutique.orange.fr/accessoires/manette-gamer-sans-fil)

**What happens instead of that?**
Here's a mapping which seems to work, Nevertheless I'm not sure about the dpup/dpdown/dpleft/dpright. When I'm testing dpleft for example in jstest : 
Axes:  0:     0  1:     0  2:     0  3: 32767  4: 32767  5:     0  6:**-32767**  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off
And dpup :
Axes:  0:     0  1:     0  2:     0  3: 32767  4: 32767  5:     0  6:     0  7:**-32767** Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off

Should I set dpup:a7,dpdown:a7,dpleft:a6,dpright:a6

Here's my current version inspired from default mapping :
**030000006b14000001a1000011010000,DEvice Orange Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,start:b9,back:b8,guide:b10,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftshoulder:b4,rightshoulder:b5,lefttrigger:a3,righttrigger:a4,leftstick:b6,rightstick:b7,leftx:a0,lefty:a1,rightx:a5,righty:a2,**

**Comment by irtimmer** [comment]
Controller mappings are imported from https://github.com/gabomdq/SDL_GameControllerDB Therefore new controller mappings needs to be submitted to them.
