### ISSUE TITLE
Impossible to stream when I use VPN on PC 

### ISSUE THREAD

**Issue by whiteorino** [irtimmer/moonlight-embedded#680]
Hello,

**My moonlight stream work properly in normal time.**
But recently I wanted to use VPN on my PC, and when I use VPN ( NordVPN ) on my PC, I can't connect moonlight on the raspberry.

_pi@raspberrypi:~ $ moonlight stream -1080
Searching for server..._

And nothing more than this, I have to CTRL+C to stop.

I think there is a routing issue but I don't know which one.

Can you help me guys ?

**Comment by irtimmer** [comment]
add the ip address of the pc at the end of the moonlight commend so you don't depend on automatic discovery.
