### ISSUE TITLE
Release with X1 and X2 buttons on archive.itimmer.nl

### ISSUE THREAD

**Issue by seaverd** [irtimmer/moonlight-embedded#697]
So my son is very interested in the latest commits that add the thumb buttons x1 and x2 to moonlight.

I attempted to compile myself and was unsuccessful.  How often is a compiled package uploaded to:

http://archive.itimmer.nl/raspbian/moonlight

It looks like the most recent version pushed here is January 2018....the August release was not pushed to the above site.  Just wondering when I might be able to expect a version to be pushed with the X1 and X2 buttons.  

In the meantime, I will keep trying to get it to compile.

Thanks,
Dan

**Comment by irtimmer** [comment]
version 2.4.8 have been released
