### ISSUE TITLE
Compile Assistance

### ISSUE THREAD

**Issue by seaverd** [irtimmer/moonlight-embedded#700]
I am following the wiki compile guide and have two issues:

1. cannot find these two dependencies:  rbp-userland-osmc and rbp-userland-dev-osmc
2. went forward with cmake ../ and I get the following output:

` sudo cmake ../
-- Could NOT find Freescale (missing:  FREESCALE_INCLUDE_DIR KERNEL_INCLUDE_DIR VPU_LIBRARY)
-- Could NOT find Amlogic (missing:  AMLOGIC_INCLUDE_DIR AMCODEC_LIBRARY AMADEC_LIBRARY AMAVUTILS_LIBRARY)
-- Could NOT find Rockchip (missing:  ROCKCHIP_INCLUDE_DIR ROCKCHIP_LIBRARY)
-- Checking for module 'sdl2>=2.0.4'
--
-- Checking for module 'libavcodec'
--   No package 'libavcodec' found
-- Checking for module 'libavutil'
--   No package 'libavutil' found
-- Checking for module 'x11'
--   No package 'x11' found
-- Checking for module 'vdpau'
--   No package 'vdpau' found
-- Checking for module 'libva'
--   No package 'libva' found
-- Checking for module 'libva-x11'
--   No package 'libva-x11' found
-- Checking for module 'libcec>=4'
--
-- Checking for module 'egl'
--   No package 'egl' found
-- Checking for module 'glesv2'
--   No package 'glesv2' found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/moonlight-embedded/build
`

Are these additional packages that are necessary?  I tried to install many of them and get unable to locate package?

Any suggestions would be greatly appreciated!

Thanks,
Dan

**Comment by irtimmer** [comment]
No, either libraspberrypi0 or rbp-userland-osmc is required when running on the Raspberry Pi. All the other packages are optional and are only necessary when you try to run Moonlight Embedded on other types of devices.
