### ISSUE TITLE
Update gamecontrollerdb.txt

### ISSUE THREAD

**Issue by TyanColte** [irtimmer/moonlight-embedded#714]
Please provide the following info.

**_NVidia Geforce Experience version:_** _3.16_
**Moonlight Embedded version:** _Any_
**Moonlight Embedded source:** _repository_
**Moonlight Embedded running on:** _Raspberry Pi 3B+_
**Moonlight Embedded running on distribution:** _Raspbian Latest_

**Verbose output `-verbose` of Moonlight Embedded:** _Not necessary_

**What is the expected result?**
XBox One Elite Controller Maps successfully
**What happens instead of that?**
gamecontrollerdb.txt file does not have the required maps in the current build of Moonlight-embedded to map the xbox one elite controller. I have already successfully sent a pull request to sdl_gamecontrollerdb with the proper mapping. Please update the gamecontrollersdb.txt to fix this issue. Thanks @irtimmer

**Comment by irtimmer** [comment]
Fixed with commit a5ea38cb281a791de269804130e1d601f9817b64
