### ISSUE TITLE
I have no idea how to actually launch the app

### ISSUE THREAD

**Issue by Captskuzz** [irtimmer/moonlight-embedded#719]
Please provide the following info.

**_NVidia Geforce Experience version:_** latest
**Moonlight Embedded version:** I installed following this guide https://github.com/irtimmer/moonlight-embedded/issues/716

..._
**Moonlight Embedded running on:** _Raspberry P..._
**Moonlight Embedded running on distribution:** _Arch Linux/Raspbian/OpenELEC/..._

**Verbose output `-verbose` of Moonlight Embedded:**

**What is the expected result?**
Moonlight did not add any options to launch from emulationstation and I have no idea how to launch the app. 
**What happens instead of that?**

**Comment by hayleyhailstorm** [comment]
Hey Captskuzz, you should be able to launch Moonlight by opening up terminal on your raspberry pi and running "moonlight stream" if you've gone through and paired the computer and all that. https://www.howtogeek.com/241300/how-to-stream-games-with-nvidia-gamestream-to-any-computer-tablet-or-smartphone/ has more info!
