### ISSUE TITLE
-localaudio not working

### ISSUE THREAD

**Issue by McNugget6750** [irtimmer/moonlight-embedded#736]
Raspberry Pi 3 on latest Raspbian Stretch using latest Moonlight Master minus https://github.com/irtimmer/moonlight-embedded/issues/734#issuecomment-464511822

Starting and streaming moonlight games, or in my case mstsc.exe using the argument -localaudio does still play audio on my host PC.

Host PC uses latest GeForce Experience 3.17.0.126

**Comment by richri** [comment]
I may be wrong, but isn't that what the switch -localaudio ist meant for? to play audio on the host PC rather than streaming it and play ist on the TV or whereever you run moonlight-embedded?
