### ISSUE TITLE
module script.moonlight 2.4.9

### ISSUE THREAD

**Issue by ssAxl** [irtimmer/moonlight-embedded#748]
Hi,

Is there a chance to have a script.moonlight 2.4.9 for Librelec?
The last is 2.4.7

Thanks!

**Comment by kurac338** [comment]
I dont think this is the right repository for this question.
I believe that "script.moonlight" was developed by "dead". If you know who the author is, you need to redirect that question to them. If you don't know who made it, some clues can be found inside the scripts resource files.

**Comment by ssAxl** [comment]
Hello,
You're right, I fooled myself.
Thank you for the information!
