### ISSUE TITLE
[Feature] Option to disable input

### ISSUE THREAD

**Issue by tadly** [irtimmer/moonlight-embedded#761]
Would it be possible to add an option to ignore all input?

I use moonlight **just** as a video feed while using peripherals directly connected to the client and would like to ensure not interference between the two input *methods*.

**Comment by yukatan** [comment]
I'm do it this just using steam. You can go to gamepad config and hide any control you don't want to use

**Comment by hhromic** [comment]
Hi, I just implemented such an option now in Moonlight embedded. See the referenced PR.
Testing and feedback is appreciated. Thanks!

The new command-line option is `-viewonly` and it can also be stored in config using `viewonly = true`.

**Comment by tadly** [comment]
@yukatan for what I'm doing, steam is waaaaay to bloated but nice to know you can do that

@hhromic awesome, I have a super busy schedule but hope I can get around testing it sometime soon.
Thanks a lot for working on this :)

**Comment by hhromic** [comment]
@tadly ah dang :/
Whenever I get access to an X11-based computer I'll try to implement the feature there.
Sorry the current implementation doesn't apply to you at the moment.
