### ISSUE TITLE
Buster package not available.

### ISSUE THREAD

**Issue by greigs** [irtimmer/moonlight-embedded#768]
I was hoping to install the package for buster but it isn't available here - http://archive.itimmer.nl/raspbian/moonlight/dists/

**Comment by discordianfish** [comment]
@irtimmer Is the tooling to build the debian packages included in this repo somewhere? If so, I could look into building a buster package but would rather not start from scratch :)

**Comment by irtimmer** [comment]
Duplicate of #750
