### ISSUE TITLE
client mouse cursor stays visible

### ISSUE THREAD

**Issue by payonel** [irtimmer/moonlight-embedded#791]
**_NVidia Geforce Experience version:_** 3.20.3.63
**Moonlight Embedded version:** 2.4.10
**Moonlight Embedded source:** https://github.com/irtimmer/moonlight-embedded/wiki/Packages
**Moonlight Embedded running on:** rpi 4B, 4GB RAM
**Moonlight Embedded running on distribution:** rpi os 32bit https://www.raspberrypi.org/downloads/raspberry-pi-os/ (buster)

**Verbose output `-verbose` of Moonlight Embedded:** 
Moonlight Embedded 2.4.10 (PI;ALSA;EMBEDDED)
Searching for server...
Connect to 192.168.8.172...
NVIDIA GeForce GTX 1080, GFE 3.20.3.63 (gs_04_22_28196077, 7.1.422.0)
Platform Raspberry Pi (Broadcom)
Loading mappingfile /usr/share/moonlight/gamecontrollerdb.txt
No mapping available for Logitech Logitech G633 Gaming Headset Consumer Control (030000006d0400005c0a000011010000) on /dev/input/event9
No mapping available for Logitech Logitech G633 Gaming Headset (030000006d0400005c0a000011010000) on /dev/input/event10
No mapping available for Corsair CORSAIR M65 RGB ELITE Gaming Mouse (030000001c1b00005a1b000011010000) on /dev/input/event3
No mapping available for Corsair CORSAIR M65 RGB ELITE Gaming Mouse (030000001c1b00005a1b000011010000) on /dev/input/event4
Stream 1280 x 720, 30 fps, 5000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...done
Starting input stream...done
Alsa error from writei: -32
Server notified termination reason: 0x0100
Control stream received disconnect event
Stopping input stream...done
Stopping audio stream...Failed to send ENet control packet
Loss Stats: Transaction failed: 0
done
Stopping video stream...done
Stopping control stream...done
Cleaning up input stream...done
Cleaning up audio stream...done
Cleaning up video stream...done
Cleaning up control stream...done
Cleaning up platform...done
Sending app quit request ...

**What is the expected result?**
client cursor is hidden.

**What happens instead of that?**
client cursor remains stuck in the screen where it was last visible

Thus, I see two cursors. The client cursor remains where it was last displayed. It does not act nor move. The host cursor (as desired) is fully functional. My solution has been to try to remember to move my cursor to the edge of the screen before I run moonlight. I often forget

**Comment by irtimmer** [comment]
Moonlight Embedded isn't a desktop application and is expected to be run from the console on the Raspberry Pi. As it is not a X11 or Wayland application Moonlight Embedded isn't aware of the drawn client cursor. Therefore running Moonlight Embedded in an desktop environment is currently unsupported.

Note: on systems, where SDL is used for the display output, Moonlight Embedded is running as an desktop application.
