### ISSUE TITLE
Version not bumped to 2.4.11

### ISSUE THREAD

**Issue by lobre** [irtimmer/moonlight-embedded#794]
Hello,

Just throwing this rapidly here. I am not a C/C++ developer but it feels version has not been upgraded for v2.4.11 tag in the build file:
https://github.com/irtimmer/moonlight-embedded/blob/v2.4.11/CMakeLists.txt#L2

If you confirm, I can take the time to submit a quick PR.

This leads to `moonlight help` showing:
```
Moonlight Embedded 2.4.10
Usage...
```

While I have 2.4.11 features (`-viewonly` flag).

Loric

**Comment by irtimmer** [comment]
It's know the version number hasn't been updated with the latest release. Issue will be fixed with the release of version 2.4.12/2.5.0/3.0
