### ISSUE TITLE
How to start non-steam apps?

### ISSUE THREAD

**Issue by Warchant** [irtimmer/moonlight-embedded#811]
**_NVidia Geforce Experience version:_** 3.21.0.36
**Moonlight Embedded version:** 2.4.10
**Moonlight Embedded source:** from buster dist
**Moonlight Embedded running on:** Raspberry PI 4
**Moonlight Embedded running on distribution:** Raspbian

When I type `moonlight stream`, Steam "Big Picture" starts, as expected. But it only lists games available in Steam.

How to start non-steam apps/games?

`moonlight list` outputs correct list of games though.

**Comment by btcooper22** [comment]
does `moonlight stream -app appname` work? Where `appname` is a name from the output of `moonlight list`
