### ISSUE TITLE
[Recalbox] [W10] [raspi2] blackscreen stream

### ISSUE THREAD

**Issue by Kiri85** [irtimmer/moonlight-embedded#813]
Hello,

I have a problem since yesterday.
I have recalbox OS on raspi 2 (connexion with RJ45).
I launch moonlight, stream begin and after i have à black screen on my tv.
I update nvidia drivers and software on my pc but doesn't work.

Do you have solution or idea about the problem ?

Tank you for you time and answer.

**Comment by aidenator** [comment]
FYI, this was fixed for me by pulling the latest version. Thanks, devs!
