### ISSUE TITLE
Don't show mouse cursor

### ISSUE THREAD

**Issue by djemix** [irtimmer/moonlight-embedded#92]
Hello! I'm running Limelighton Raspberry Pi 2.

It run perfect! But It don't show the mouse cursor of the computer server.
I only see the cursor of Steram Big Picture, but when I launch a game, I can't see the mouse cursor in the game.

Do I need to configure something?

**Comment by cgutman** [comment]
Does your PC have a mouse plugged in?

**Comment by djemix** [comment]
Of course!
Indeed, I run the client on another computer Limelight with the PC version and working properly, the computer cursor is.
It does not look when I run Limelight embedded in the Rabesperry.
