### ISSUE TITLE
Not paired

### ISSUE THREAD

**Issue by matigev** [irtimmer/moonlight-embedded#93]
First of all: Thanks for this great piece of software!
I'm currently running on Raspberry Pi 2 (Raspbian), but I'm experiencing some weird behaviour when running from /etc/rc.local. I get the error "not paired", but when I ssh to my pi no problems at all with the same command. Anyone knows why?
Previously I ran on Pi B+ (older Raspbian) with no errors at all.

**Comment by gforced** [comment]
having same issue

**Comment by matigev** [comment]
I figured it out finally. First cd to the jar directory! For example in my rc.local:
cd /home/pi
sudo java -jar limelight.jar stream &

**Comment by matigev** [comment]
With the new c versions I am getting this error again.. cd'ing to the right dir or setting the PATH won't work. When I put moonlight pair in front of it, it says "Already paired". Is there any way to point moonlight to the right certificate files?

**Comment by matigev** [comment]
Never mind, I figured it out myself... you can use 
-keydir /path/to/dir
