### ISSUE TITLE
Limelight-embedded Raspian install script

### ISSUE THREAD

**Issue by stsfin** [irtimmer/moonlight-embedded#96]
Hi,

I made a configurator and install script for rasbian based systems:

https://github.com/stsfin/LimelightPiInstaller

This should help with issues (finding the right event etc) for first timers to get limelight working... This could be forked to work with other systems as well

**Comment by stsfin** [comment]
@irtimmer hope you can fork it further.. My knowledge of other (read rpm based) systems is limited.

**Comment by RoelofBerg** [comment]
Cool, thanks for figuring out how to 1080p@60Hz :) I might add this to my setup tutorial at http://embedded-software-architecture.com/?page_id=140

**Comment by stsfin** [comment]
Naturally yes!

**Comment by barryownt** [comment]
Thanks bro i think this would be helpful for a lot of people !
